export interface FlashcardItem {
  id: string;
  english: string;
  french?: string;
  arabic?: string;
  target: string;
  alternatives?: string[];
  dialect?: string;
  transliteration?: string;
  /** Optional user-supplied audio (recorded or uploaded), stored as a data URI. */
  audioUrl?: string;
  /** Optional illustration for context-based guessing */
  imageUrl?: string;
}

export interface Level {
  id: string;
  title: string;
  cefr?: "A1" | "A2" | "B1";
  cards: FlashcardItem[];
}

// ─────────────────────────────────────────────────────────────────────────────
// FRENCH — VOCABULARY LEVELS
// ─────────────────────────────────────────────────────────────────────────────

export const vocabularyLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-a1-1",
    title: "A1 · Greetings & basics",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-1-c01", english: "Hello / Good day",       target: "Bonjour" },
      { id: "fr-v-a1-1-c02", english: "Good evening",           target: "Bonsoir" },
      { id: "fr-v-a1-1-c03", english: "Hi / Bye (informal)",    target: "Salut" },
      { id: "fr-v-a1-1-c04", english: "Goodbye",                target: "Au revoir" },
      { id: "fr-v-a1-1-c05", english: "See you soon",           target: "À bientôt" },
      { id: "fr-v-a1-1-c06", english: "See you tomorrow",       target: "À demain" },
      { id: "fr-v-a1-1-c07", english: "Please",                 target: "S'il vous plaît", alternatives: ["S'il te plaît"] },
      { id: "fr-v-a1-1-c08", english: "Thank you",              target: "Merci" },
      { id: "fr-v-a1-1-c09", english: "Thank you very much",    target: "Merci beaucoup" },
      { id: "fr-v-a1-1-c10", english: "You're welcome",         target: "De rien" },
      { id: "fr-v-a1-1-c11", english: "Sorry / Excuse me",      target: "Pardon" },
      { id: "fr-v-a1-1-c12", english: "Excuse me (formal)",     target: "Excusez-moi" },
      { id: "fr-v-a1-1-c13", english: "Yes",                    target: "Oui" },
      { id: "fr-v-a1-1-c14", english: "No",                     target: "Non" },
      { id: "fr-v-a1-1-c15", english: "OK / alright",           target: "D'accord" },
    ],
  },

  {
    id: "fr-v-a1-2",
    title: "A1 · Numbers & time",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-2-c01", english: "One",                    target: "Un" },
      { id: "fr-v-a1-2-c02", english: "Two",                    target: "Deux" },
      { id: "fr-v-a1-2-c03", english: "Three",                  target: "Trois" },
      { id: "fr-v-a1-2-c04", english: "Four",                   target: "Quatre" },
      { id: "fr-v-a1-2-c05", english: "Five",                   target: "Cinq" },
      { id: "fr-v-a1-2-c06", english: "Ten",                    target: "Dix" },
      { id: "fr-v-a1-2-c07", english: "Twenty",                 target: "Vingt" },
      { id: "fr-v-a1-2-c08", english: "Thirty",                 target: "Trente" },
      { id: "fr-v-a1-2-c09", english: "One hundred",            target: "Cent" },
      { id: "fr-v-a1-2-c10", english: "One thousand",           target: "Mille" },
      { id: "fr-v-a1-2-c11", english: "What time is it?",       target: "Quelle heure est-il" },
      { id: "fr-v-a1-2-c12", english: "It is 3 o'clock",        target: "Il est trois heures" },
      { id: "fr-v-a1-2-c13", english: "In the morning",         target: "Du matin" },
      { id: "fr-v-a1-2-c14", english: "In the afternoon",       target: "De l'après-midi" },
      { id: "fr-v-a1-2-c15", english: "At noon",                target: "À midi" },
      { id: "fr-v-a1-2-c16", english: "At midnight",            target: "À minuit" },
      { id: "fr-v-a1-2-c17", english: "Half past",              target: "Et demie" },
      { id: "fr-v-a1-2-c18", english: "Quarter past",           target: "Et quart" },
    ],
  },

  {
    id: "fr-v-a1-3",
    title: "A1 · Days & months",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-3-c01", english: "Monday",                 target: "Lundi" },
      { id: "fr-v-a1-3-c02", english: "Tuesday",                target: "Mardi" },
      { id: "fr-v-a1-3-c03", english: "Wednesday",              target: "Mercredi" },
      { id: "fr-v-a1-3-c04", english: "Thursday",               target: "Jeudi" },
      { id: "fr-v-a1-3-c05", english: "Friday",                 target: "Vendredi" },
      { id: "fr-v-a1-3-c06", english: "Saturday",               target: "Samedi" },
      { id: "fr-v-a1-3-c07", english: "Sunday",                 target: "Dimanche" },
      { id: "fr-v-a1-3-c08", english: "Today",                  target: "Aujourd'hui" },
      { id: "fr-v-a1-3-c09", english: "Tomorrow",               target: "Demain" },
      { id: "fr-v-a1-3-c10", english: "Yesterday",              target: "Hier" },
      { id: "fr-v-a1-3-c11", english: "This week",              target: "Cette semaine" },
      { id: "fr-v-a1-3-c12", english: "Next week",              target: "La semaine prochaine" },
      { id: "fr-v-a1-3-c13", english: "January",                target: "Janvier" },
      { id: "fr-v-a1-3-c14", english: "February",               target: "Février" },
      { id: "fr-v-a1-3-c15", english: "March",                  target: "Mars" },
      { id: "fr-v-a1-3-c16", english: "June",                   target: "Juin" },
      { id: "fr-v-a1-3-c17", english: "December",               target: "Décembre" },
      { id: "fr-v-a1-3-c18", english: "Now",                    target: "Maintenant" },
      { id: "fr-v-a1-3-c19", english: "Soon",                   target: "Bientôt" },
      { id: "fr-v-a1-3-c20", english: "Always / never",         target: "Toujours", alternatives: ["Jamais"] },
    ],
  },

  {
    id: "fr-v-a1-4",
    title: "A1 · Core verbs",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-4-c01", english: "To be",                  target: "Être" },
      { id: "fr-v-a1-4-c02", english: "To have",                target: "Avoir" },
      { id: "fr-v-a1-4-c03", english: "To go",                  target: "Aller" },
      { id: "fr-v-a1-4-c04", english: "To do / make",           target: "Faire" },
      { id: "fr-v-a1-4-c05", english: "To want",                target: "Vouloir" },
      { id: "fr-v-a1-4-c06", english: "To be able to",          target: "Pouvoir" },
      { id: "fr-v-a1-4-c07", english: "To know (a fact)",       target: "Savoir" },
      { id: "fr-v-a1-4-c08", english: "To know (a person)",     target: "Connaître" },
      { id: "fr-v-a1-4-c09", english: "To come",                target: "Venir" },
      { id: "fr-v-a1-4-c10", english: "To see",                 target: "Voir" },
      { id: "fr-v-a1-4-c11", english: "To speak",               target: "Parler" },
      { id: "fr-v-a1-4-c12", english: "To eat",                 target: "Manger" },
      { id: "fr-v-a1-4-c13", english: "To drink",               target: "Boire" },
      { id: "fr-v-a1-4-c14", english: "To live / stay",         target: "Habiter" },
      { id: "fr-v-a1-4-c15", english: "To need / must",         target: "Devoir" },
    ],
  },

  {
    id: "fr-v-a1-5",
    title: "A1 · People & family",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-5-c01", english: "Man",                    target: "Un homme" },
      { id: "fr-v-a1-5-c02", english: "Woman",                  target: "Une femme" },
      { id: "fr-v-a1-5-c03", english: "Child",                  target: "Un enfant" },
      { id: "fr-v-a1-5-c04", english: "Boy",                    target: "Un garçon" },
      { id: "fr-v-a1-5-c05", english: "Girl",                   target: "Une fille" },
      { id: "fr-v-a1-5-c06", english: "Friend",                 target: "Un ami", alternatives: ["Une amie"] },
      { id: "fr-v-a1-5-c07", english: "Father",                 target: "Le père" },
      { id: "fr-v-a1-5-c08", english: "Mother",                 target: "La mère" },
      { id: "fr-v-a1-5-c09", english: "Brother",                target: "Le frère" },
      { id: "fr-v-a1-5-c10", english: "Sister",                 target: "La sœur" },
      { id: "fr-v-a1-5-c11", english: "Parents",                target: "Les parents" },
      { id: "fr-v-a1-5-c12", english: "Family",                 target: "La famille" },
      { id: "fr-v-a1-5-c13", english: "Grandfather",            target: "Le grand-père" },
      { id: "fr-v-a1-5-c14", english: "My name is",             target: "Je m'appelle" },
      { id: "fr-v-a1-5-c15", english: "I am ... years old",     target: "J'ai ... ans" },
    ],
  },

  {
    id: "fr-v-a1-6",
    title: "A1 · Food & drink",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-6-c01", english: "Water",                  target: "De l'eau" },
      { id: "fr-v-a1-6-c02", english: "Coffee",                 target: "Un café" },
      { id: "fr-v-a1-6-c03", english: "Tea",                    target: "Un thé" },
      { id: "fr-v-a1-6-c04", english: "Wine",                   target: "Du vin" },
      { id: "fr-v-a1-6-c05", english: "Beer",                   target: "Une bière" },
      { id: "fr-v-a1-6-c06", english: "Bread",                  target: "Du pain" },
      { id: "fr-v-a1-6-c07", english: "Cheese",                 target: "Du fromage" },
      { id: "fr-v-a1-6-c08", english: "Meat",                   target: "De la viande" },
      { id: "fr-v-a1-6-c09", english: "Fish",                   target: "Du poisson" },
      { id: "fr-v-a1-6-c10", english: "Chicken",                target: "Du poulet" },
      { id: "fr-v-a1-6-c11", english: "Salad",                  target: "Une salade" },
      { id: "fr-v-a1-6-c12", english: "Dessert",                target: "Un dessert" },
      { id: "fr-v-a1-6-c13", english: "The bill",               target: "L'addition" },
      { id: "fr-v-a1-6-c14", english: "A table for two",        target: "Une table pour deux" },
      { id: "fr-v-a1-6-c15", english: "I am hungry",            target: "J'ai faim", imageUrl: "/assets/illustrations/i_am_hungry.png" },
      { id: "fr-v-a1-6-c16", english: "I am thirsty",           target: "J'ai soif" },
      { id: "fr-v-a1-6-c17", english: "Delicious",              target: "Délicieux" },
      { id: "fr-v-a1-6-c18", english: "Juice",                  target: "Un jus" },
    ],
  },

  {
    id: "fr-v-a1-7",
    title: "A1 · Places & directions",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-7-c01", english: "The city / town",        target: "La ville" },
      { id: "fr-v-a1-7-c02", english: "The street",             target: "La rue" },
      { id: "fr-v-a1-7-c03", english: "The train station",      target: "La gare", imageUrl: "/assets/illustrations/train_station.png" },
      { id: "fr-v-a1-7-c04", english: "The airport",            target: "L'aéroport" },
      { id: "fr-v-a1-7-c05", english: "The hospital",           target: "L'hôpital" },
      { id: "fr-v-a1-7-c06", english: "The pharmacy",           target: "La pharmacie" },
      { id: "fr-v-a1-7-c07", english: "The bank",               target: "La banque" },
      { id: "fr-v-a1-7-c08", english: "The supermarket",        target: "Le supermarché" },
      { id: "fr-v-a1-7-c09", english: "The hotel",              target: "L'hôtel" },
      { id: "fr-v-a1-7-c10", english: "On the left",            target: "À gauche" },
      { id: "fr-v-a1-7-c11", english: "On the right",           target: "À droite" },
      { id: "fr-v-a1-7-c12", english: "Straight ahead",         target: "Tout droit" },
      { id: "fr-v-a1-7-c13", english: "Near / close",           target: "Près" },
      { id: "fr-v-a1-7-c14", english: "Far",                    target: "Loin" },
      { id: "fr-v-a1-7-c15", english: "The toilet",             target: "Les toilettes" },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-a2-1",
    title: "A2 · Everyday adjectives",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-1-c01", english: "Good",                   target: "Bon" },
      { id: "fr-v-a2-1-c02", english: "Bad",                    target: "Mauvais" },
      { id: "fr-v-a2-1-c03", english: "Big / tall",             target: "Grand" },
      { id: "fr-v-a2-1-c04", english: "Small",                  target: "Petit" },
      { id: "fr-v-a2-1-c05", english: "New",                    target: "Nouveau" },
      { id: "fr-v-a2-1-c06", english: "Old",                    target: "Vieux" },
      { id: "fr-v-a2-1-c07", english: "Beautiful",              target: "Beau" },
      { id: "fr-v-a2-1-c08", english: "Happy",                  target: "Heureux" },
      { id: "fr-v-a2-1-c09", english: "Sad",                    target: "Triste" },
      { id: "fr-v-a2-1-c10", english: "Tired",                  target: "Fatigué" },
      { id: "fr-v-a2-1-c11", english: "Busy",                   target: "Occupé" },
      { id: "fr-v-a2-1-c12", english: "Easy",                   target: "Facile" },
      { id: "fr-v-a2-1-c13", english: "Difficult",              target: "Difficile" },
      { id: "fr-v-a2-1-c14", english: "Expensive",              target: "Cher" },
      { id: "fr-v-a2-1-c15", english: "Cheap",                  target: "Pas cher" },
      { id: "fr-v-a2-1-c16", english: "Hot",                    target: "Chaud" },
      { id: "fr-v-a2-1-c17", english: "Cold",                   target: "Froid" },
      { id: "fr-v-a2-1-c18", english: "Open",                   target: "Ouvert" },
      { id: "fr-v-a2-1-c19", english: "Closed",                 target: "Fermé" },
      { id: "fr-v-a2-1-c20", english: "Interesting",            target: "Intéressant" },
    ],
  },

  {
    id: "fr-v-a2-2",
    title: "A2 · Daily routine",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-2-c01", english: "To wake up",             target: "Se réveiller" },
      { id: "fr-v-a2-2-c02", english: "To get up",              target: "Se lever" },
      { id: "fr-v-a2-2-c03", english: "To shower",              target: "Se doucher" },
      { id: "fr-v-a2-2-c04", english: "To get dressed",         target: "S'habiller" },
      { id: "fr-v-a2-2-c05", english: "To have breakfast",      target: "Prendre le petit-déjeuner" },
      { id: "fr-v-a2-2-c06", english: "To work",                target: "Travailler" },
      { id: "fr-v-a2-2-c07", english: "To study",               target: "Étudier" },
      { id: "fr-v-a2-2-c08", english: "To come back home",      target: "Rentrer à la maison" },
      { id: "fr-v-a2-2-c09", english: "To cook",                target: "Cuisiner", alternatives: ["Faire la cuisine"] },
      { id: "fr-v-a2-2-c10", english: "To watch TV",            target: "Regarder la télé" },
      { id: "fr-v-a2-2-c11", english: "To read",                target: "Lire" },
      { id: "fr-v-a2-2-c12", english: "To go to bed",           target: "Se coucher" },
      { id: "fr-v-a2-2-c13", english: "To sleep",               target: "Dormir" },
      { id: "fr-v-a2-2-c14", english: "To call (phone)",        target: "Appeler", alternatives: ["Téléphoner"] },
      { id: "fr-v-a2-2-c15", english: "To take the bus",        target: "Prendre le bus" },
    ],
  },

  {
    id: "fr-v-a2-3",
    title: "A2 · Shopping & money",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-3-c01", english: "To buy",                 target: "Acheter" },
      { id: "fr-v-a2-3-c02", english: "To pay",                 target: "Payer" },
      { id: "fr-v-a2-3-c03", english: "To cost",                target: "Coûter" },
      { id: "fr-v-a2-3-c04", english: "The price",              target: "Le prix" },
      { id: "fr-v-a2-3-c05", english: "Cash",                   target: "En espèces", alternatives: ["En liquide"] },
      { id: "fr-v-a2-3-c06", english: "Card payment",           target: "Par carte" },
      { id: "fr-v-a2-3-c07", english: "A receipt",              target: "Un reçu", alternatives: ["Un ticket"] },
      { id: "fr-v-a2-3-c08", english: "On sale",                target: "En solde" },
      { id: "fr-v-a2-3-c09", english: "The size",               target: "La taille" },
      { id: "fr-v-a2-3-c10", english: "Too big",                target: "Trop grand" },
      { id: "fr-v-a2-3-c11", english: "Too small",              target: "Trop petit" },
      { id: "fr-v-a2-3-c12", english: "I'm just looking",       target: "Je regarde seulement" },
      { id: "fr-v-a2-3-c13", english: "I'll take it",           target: "Je le prends" },
      { id: "fr-v-a2-3-c14", english: "Can I return this?",     target: "Je peux le rendre" },
      { id: "fr-v-a2-3-c15", english: "The change",             target: "La monnaie" },
    ],
  },

  {
    id: "fr-v-a2-4",
    title: "A2 · Transport & travel",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-4-c01", english: "The train",              target: "Le train" },
      { id: "fr-v-a2-4-c02", english: "The bus",                target: "Le bus" },
      { id: "fr-v-a2-4-c03", english: "The metro",              target: "Le métro" },
      { id: "fr-v-a2-4-c04", english: "The taxi",               target: "Le taxi" },
      { id: "fr-v-a2-4-c05", english: "The car",                target: "La voiture" },
      { id: "fr-v-a2-4-c06", english: "The plane",              target: "L'avion" },
      { id: "fr-v-a2-4-c07", english: "A single ticket",        target: "Un aller simple" },
      { id: "fr-v-a2-4-c08", english: "A return ticket",        target: "Un aller-retour" },
      { id: "fr-v-a2-4-c09", english: "The platform",           target: "Le quai" },
      { id: "fr-v-a2-4-c10", english: "The departure",          target: "Le départ" },
      { id: "fr-v-a2-4-c11", english: "The arrival",            target: "L'arrivée" },
      { id: "fr-v-a2-4-c12", english: "On time",                target: "À l'heure" },
      { id: "fr-v-a2-4-c13", english: "Late",                   target: "En retard" },
      { id: "fr-v-a2-4-c14", english: "A passport",             target: "Un passeport" },
      { id: "fr-v-a2-4-c15", english: "The luggage",            target: "Les bagages" },
    ],
  },

  {
    id: "fr-v-a2-5",
    title: "A2 · Health & body",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-5-c01", english: "I have a headache",      target: "J'ai mal à la tête" },
      { id: "fr-v-a2-5-c02", english: "I have a stomach ache",  target: "J'ai mal au ventre" },
      { id: "fr-v-a2-5-c03", english: "I feel sick",            target: "Je me sens mal" },
      { id: "fr-v-a2-5-c04", english: "I have a fever",         target: "J'ai de la fièvre" },
      { id: "fr-v-a2-5-c05", english: "A cold",                 target: "Un rhume" },
      { id: "fr-v-a2-5-c06", english: "The doctor",             target: "Le médecin" },
      { id: "fr-v-a2-5-c07", english: "A medicine",             target: "Un médicament" },
      { id: "fr-v-a2-5-c08", english: "An appointment",         target: "Un rendez-vous" },
      { id: "fr-v-a2-5-c09", english: "The head",               target: "La tête" },
      { id: "fr-v-a2-5-c10", english: "The back",               target: "Le dos" },
      { id: "fr-v-a2-5-c11", english: "The arm",                target: "Le bras" },
      { id: "fr-v-a2-5-c12", english: "The leg",                target: "La jambe" },
      { id: "fr-v-a2-5-c13", english: "To rest",                target: "Se reposer" },
      { id: "fr-v-a2-5-c14", english: "Allergic to",            target: "Allergique à" },
      { id: "fr-v-a2-5-c15", english: "It hurts here",          target: "J'ai mal ici" },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-b1-1",
    title: "B1 · Conversation connectors",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-1-c01", english: "So / then",              target: "Alors" },
      { id: "fr-v-b1-1-c02", english: "Well / right",           target: "Bon", alternatives: ["Ben"] },
      { id: "fr-v-b1-1-c03", english: "There you go",           target: "Voilà" },
      { id: "fr-v-b1-1-c04", english: "So / therefore (spoken)",target: "Du coup" },
      { id: "fr-v-b1-1-c05", english: "Actually / in fact",     target: "En fait" },
      { id: "fr-v-b1-1-c06", english: "Besides / moreover",     target: "En plus" },
      { id: "fr-v-b1-1-c07", english: "However / but",          target: "Par contre", alternatives: ["Mais"] },
      { id: "fr-v-b1-1-c08", english: "For example",            target: "Par exemple" },
      { id: "fr-v-b1-1-c09", english: "That's why",             target: "C'est pour ça que" },
      { id: "fr-v-b1-1-c10", english: "I mean / that is",       target: "C'est-à-dire" },
      { id: "fr-v-b1-1-c11", english: "To be honest",           target: "Franchement", alternatives: ["Honnêtement"] },
      { id: "fr-v-b1-1-c12", english: "In my opinion",          target: "À mon avis" },
      { id: "fr-v-b1-1-c13", english: "I think that",           target: "Je pense que", alternatives: ["Je crois que"] },
      { id: "fr-v-b1-1-c14", english: "It depends",             target: "Ça dépend" },
      { id: "fr-v-b1-1-c15", english: "Not really",             target: "Pas vraiment" },
      { id: "fr-v-b1-1-c16", english: "Exactly",                target: "Exactement", alternatives: ["Justement"] },
      { id: "fr-v-b1-1-c17", english: "More or less",           target: "Plus ou moins" },
      { id: "fr-v-b1-1-c18", english: "In general",             target: "En général" },
      { id: "fr-v-b1-1-c19", english: "At the same time",       target: "En même temps" },
      { id: "fr-v-b1-1-c20", english: "On the other hand",      target: "D'un autre côté" },
    ],
  },

  {
    id: "fr-v-b1-2",
    title: "B1 · Work & professional",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-2-c01", english: "A job / position",       target: "Un poste", alternatives: ["Un emploi"] },
      { id: "fr-v-b1-2-c02", english: "A company",              target: "Une entreprise", alternatives: ["Une société"] },
      { id: "fr-v-b1-2-c03", english: "A meeting",              target: "Une réunion" },
      { id: "fr-v-b1-2-c04", english: "A client",               target: "Un client" },
      { id: "fr-v-b1-2-c05", english: "A colleague",            target: "Un collègue" },
      { id: "fr-v-b1-2-c06", english: "The boss",               target: "Le patron", alternatives: ["Le chef"] },
      { id: "fr-v-b1-2-c07", english: "To work from home",      target: "Travailler à distance", alternatives: ["En télétravail"] },
      { id: "fr-v-b1-2-c08", english: "A deadline",             target: "Une date limite", alternatives: ["Un délai"] },
      { id: "fr-v-b1-2-c09", english: "A project",              target: "Un projet" },
      { id: "fr-v-b1-2-c10", english: "A salary",               target: "Un salaire" },
      { id: "fr-v-b1-2-c11", english: "To apply for a job",     target: "Postuler à un emploi" },
      { id: "fr-v-b1-2-c12", english: "An interview",           target: "Un entretien" },
      { id: "fr-v-b1-2-c13", english: "To hire",                target: "Embaucher", alternatives: ["Recruter"] },
      { id: "fr-v-b1-2-c14", english: "To resign",              target: "Démissionner" },
      { id: "fr-v-b1-2-c15", english: "A contract",             target: "Un contrat" },
      { id: "fr-v-b1-2-c16", english: "Leave / holiday",        target: "Un congé", alternatives: ["Des vacances"] },
      { id: "fr-v-b1-2-c17", english: "Self-employed",          target: "Indépendant", alternatives: ["Freelance"] },
      { id: "fr-v-b1-2-c18", english: "To manage / lead",       target: "Gérer", alternatives: ["Diriger"] },
    ],
  },

  {
    id: "fr-v-b1-3",
    title: "B1 · Emotions & feelings",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-3-c01", english: "I feel...",              target: "Je me sens" },
      { id: "fr-v-b1-3-c02", english: "Stressed",               target: "Stressé", alternatives: ["Anxieux"] },
      { id: "fr-v-b1-3-c03", english: "Excited",                target: "Enthousiaste", alternatives: ["Excité"] },
      { id: "fr-v-b1-3-c04", english: "Disappointed",           target: "Déçu" },
      { id: "fr-v-b1-3-c05", english: "Surprised",              target: "Surpris" },
      { id: "fr-v-b1-3-c06", english: "Relieved",               target: "Soulagé" },
      { id: "fr-v-b1-3-c07", english: "Proud",                  target: "Fier" },
      { id: "fr-v-b1-3-c08", english: "Worried",                target: "Inquiet" },
      { id: "fr-v-b1-3-c09", english: "Bored",                  target: "Je m'ennuie", alternatives: ["Ennuyé"] },
      { id: "fr-v-b1-3-c10", english: "Angry",                  target: "En colère", alternatives: ["Fâché"] },
      { id: "fr-v-b1-3-c11", english: "Nervous",                target: "Nerveux" },
      { id: "fr-v-b1-3-c12", english: "Comfortable",            target: "À l'aise" },
      { id: "fr-v-b1-3-c13", english: "I miss you",             target: "Tu me manques" },
      { id: "fr-v-b1-3-c14", english: "To love (something)",    target: "Adorer", alternatives: ["J'adore"] },
      { id: "fr-v-b1-3-c15", english: "To hate",                target: "Détester", alternatives: ["J'ai horreur de"] },
    ],
  },

  {
    id: "fr-v-b1-4",
    title: "B1 · Technology",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-4-c01", english: "A smartphone",           target: "Un smartphone", alternatives: ["Un téléphone"] },
      { id: "fr-v-b1-4-c02", english: "The internet",           target: "Internet" },
      { id: "fr-v-b1-4-c03", english: "Wi-Fi",                  target: "Le Wi-Fi" },
      { id: "fr-v-b1-4-c04", english: "To send a message",      target: "Envoyer un message" },
      { id: "fr-v-b1-4-c05", english: "Social media",           target: "Les réseaux sociaux" },
      { id: "fr-v-b1-4-c06", english: "To download",            target: "Télécharger" },
      { id: "fr-v-b1-4-c07", english: "An app",                 target: "Une appli", alternatives: ["Une application"] },
      { id: "fr-v-b1-4-c08", english: "A computer",             target: "Un ordinateur" },
      { id: "fr-v-b1-4-c09", english: "A screen",               target: "Un écran" },
      { id: "fr-v-b1-4-c10", english: "A password",             target: "Un mot de passe" },
      { id: "fr-v-b1-4-c11", english: "To charge the phone",    target: "Charger le téléphone" },
      { id: "fr-v-b1-4-c12", english: "It doesn't work",        target: "Ça ne marche pas" },
      { id: "fr-v-b1-4-c13", english: "To book online",         target: "Réserver en ligne" },
      { id: "fr-v-b1-4-c14", english: "A video call",           target: "Un appel vidéo" },
      { id: "fr-v-b1-4-c15", english: "A notification",         target: "Une notification" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FRENCH — PHRASE LEVELS
// ─────────────────────────────────────────────────────────────────────────────

export const phraseLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-a1-1",
    title: "A1 · Introducing yourself",
    cefr: "A1",
    cards: [
      { id: "fr-p-a1-1-c01", english: "My name is Dave",        target: "Je m'appelle Dave" },
      { id: "fr-p-a1-1-c02", english: "I am from Uganda",       target: "Je suis ougandais", alternatives: ["Je viens d'Ouganda"] },
      { id: "fr-p-a1-1-c03", english: "I live in Cairo",        target: "J'habite au Caire" },
      { id: "fr-p-a1-1-c04", english: "I am 30 years old",      target: "J'ai trente ans" },
      { id: "fr-p-a1-1-c05", english: "Nice to meet you",       target: "Enchanté" },
      { id: "fr-p-a1-1-c06", english: "How are you? (formal)",  target: "Comment allez-vous" },
      { id: "fr-p-a1-1-c07", english: "How are you? (casual)",  target: "Ça va" },
      { id: "fr-p-a1-1-c08", english: "I'm fine, thanks",       target: "Ça va bien merci" },
      { id: "fr-p-a1-1-c09", english: "And you?",               target: "Et vous", alternatives: ["Et toi"] },
      { id: "fr-p-a1-1-c10", english: "I am a designer",        target: "Je suis designer" },
      { id: "fr-p-a1-1-c11", english: "I am learning French",   target: "J'apprends le français" },
      { id: "fr-p-a1-1-c12", english: "I am married",           target: "Je suis marié", alternatives: ["Je suis célibataire"] },
    ],
  },

  {
    id: "fr-p-a1-2",
    title: "A1 · Survival phrases",
    cefr: "A1",
    cards: [
      { id: "fr-p-a1-2-c01", english: "I don't understand",     target: "Je ne comprends pas" },
      { id: "fr-p-a1-2-c02", english: "Can you repeat?",        target: "Vous pouvez répéter" },
      { id: "fr-p-a1-2-c03", english: "Speak more slowly",      target: "Parlez plus lentement s'il vous plaît" },
      { id: "fr-p-a1-2-c04", english: "Do you speak English?",  target: "Vous parlez anglais" },
      { id: "fr-p-a1-2-c05", english: "I speak a little French",target: "Je parle un peu français" },
      { id: "fr-p-a1-2-c06", english: "Where is the bathroom?", target: "Où sont les toilettes", imageUrl: "/assets/illustrations/where_is_bathroom.png" },
      { id: "fr-p-a1-2-c07", english: "How much does it cost?", target: "C'est combien" },
      { id: "fr-p-a1-2-c08", english: "I would like...",        target: "Je voudrais" },
      { id: "fr-p-a1-2-c09", english: "Do you have...?",        target: "Vous avez" },
      { id: "fr-p-a1-2-c10", english: "Help!",                  target: "Au secours" },
      { id: "fr-p-a1-2-c11", english: "I am lost",              target: "Je suis perdu" },
      { id: "fr-p-a1-2-c12", english: "Call the police!",       target: "Appelez la police" },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-a2-1",
    title: "A2 · Making plans",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-1-c01", english: "Are you free tonight?",  target: "Tu es libre ce soir" },
      { id: "fr-p-a2-1-c02", english: "Do you want to come?",   target: "Tu veux venir" },
      { id: "fr-p-a2-1-c03", english: "I'd love to",            target: "Avec plaisir", alternatives: ["J'adorerais"] },
      { id: "fr-p-a2-1-c04", english: "Sorry, I can't",         target: "Désolé je ne peux pas" },
      { id: "fr-p-a2-1-c05", english: "Maybe another time",     target: "Peut-être une autre fois" },
      { id: "fr-p-a2-1-c06", english: "Let's meet at...",       target: "On se retrouve à" },
      { id: "fr-p-a2-1-c07", english: "I'll be there at 8",     target: "Je serai là à huit heures" },
      { id: "fr-p-a2-1-c08", english: "I'm running late",       target: "Je suis en retard" },
      { id: "fr-p-a2-1-c09", english: "I had a great time",     target: "Je me suis bien amusé" },
      { id: "fr-p-a2-1-c10", english: "It was really good",     target: "C'était vraiment bien" },
      { id: "fr-p-a2-1-c11", english: "What do you want to do?",target: "Qu'est-ce que tu veux faire" },
      { id: "fr-p-a2-1-c12", english: "I prefer...",            target: "Je préfère" },
    ],
  },

  {
    id: "fr-p-a2-2",
    title: "A2 · Talking about the past",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-2-c01", english: "I went to...",           target: "Je suis allé à" },
      { id: "fr-p-a2-2-c02", english: "I ate",                  target: "J'ai mangé" },
      { id: "fr-p-a2-2-c03", english: "I saw",                  target: "J'ai vu" },
      { id: "fr-p-a2-2-c04", english: "I did / I made",         target: "J'ai fait" },
      { id: "fr-p-a2-2-c05", english: "I bought",               target: "J'ai acheté" },
      { id: "fr-p-a2-2-c06", english: "I came back",            target: "Je suis rentré" },
      { id: "fr-p-a2-2-c07", english: "Yesterday I...",         target: "Hier j'ai" },
      { id: "fr-p-a2-2-c08", english: "Last weekend",           target: "Le week-end dernier" },
      { id: "fr-p-a2-2-c09", english: "It was (description)",   target: "C'était" },
      { id: "fr-p-a2-2-c10", english: "There was",              target: "Il y avait" },
      { id: "fr-p-a2-2-c11", english: "I didn't...",            target: "Je n'ai pas" },
      { id: "fr-p-a2-2-c12", english: "Did you...?",            target: "Tu as", alternatives: ["Vous avez"] },
    ],
  },

  {
    id: "fr-p-a2-3",
    title: "A2 · At the café",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-3-c01", english: "A coffee please",        target: "Un café s'il vous plaît" },
      { id: "fr-p-a2-3-c02", english: "What would you like?",   target: "Vous désirez" },
      { id: "fr-p-a2-3-c03", english: "The bill please",        target: "L'addition s'il vous plaît" },
      { id: "fr-p-a2-3-c04", english: "A table for two",        target: "Une table pour deux" },
      { id: "fr-p-a2-3-c05", english: "Is service included?",   target: "Le service est compris" },
      { id: "fr-p-a2-3-c06", english: "Do you have a menu?",    target: "Vous avez la carte" },
      { id: "fr-p-a2-3-c07", english: "I'll have the same",     target: "La même chose pour moi" },
      { id: "fr-p-a2-3-c08", english: "Enjoy your meal!",       target: "Bon appétit" },
      { id: "fr-p-a2-3-c09", english: "I'm vegetarian",         target: "Je suis végétarien" },
      { id: "fr-p-a2-3-c10", english: "Without meat please",    target: "Sans viande s'il vous plaît" },
      { id: "fr-p-a2-3-c11", english: "It was delicious",       target: "C'était délicieux" },
      { id: "fr-p-a2-3-c12", english: "Do you take card?",      target: "Vous prenez la carte" },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-b1-1",
    title: "B1 · Opinions & debate",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-1-c01", english: "I agree",                target: "Je suis d'accord" },
      { id: "fr-p-b1-1-c02", english: "I don't agree",          target: "Je ne suis pas d'accord" },
      { id: "fr-p-b1-1-c03", english: "You're right",           target: "Tu as raison", alternatives: ["Vous avez raison"] },
      { id: "fr-p-b1-1-c04", english: "You're wrong",           target: "Tu as tort" },
      { id: "fr-p-b1-1-c05", english: "I find that...",         target: "Je trouve que" },
      { id: "fr-p-b1-1-c06", english: "It seems to me that...", target: "Il me semble que" },
      { id: "fr-p-b1-1-c07", english: "I'm not sure",           target: "Je ne suis pas sûr" },
      { id: "fr-p-b1-1-c08", english: "That depends on...",     target: "Ça dépend de" },
      { id: "fr-p-b1-1-c09", english: "That's a good point",    target: "C'est un bon point" },
      { id: "fr-p-b1-1-c10", english: "I hadn't thought of that",target: "Je n'y avais pas pensé" },
      { id: "fr-p-b1-1-c11", english: "Let me explain",         target: "Laisse-moi expliquer" },
      { id: "fr-p-b1-1-c12", english: "What do you think?",     target: "Qu'est-ce que tu en penses" },
      { id: "fr-p-b1-1-c13", english: "Personally I think...",  target: "Personnellement je pense que" },
      { id: "fr-p-b1-1-c14", english: "On one hand...",         target: "D'un côté", alternatives: ["De l'autre"] },
    ],
  },

  {
    id: "fr-p-b1-2",
    title: "B1 · Talking about the future",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-2-c01", english: "I'm going to...",        target: "Je vais" },
      { id: "fr-p-b1-2-c02", english: "I plan to...",           target: "Je compte", alternatives: ["J'ai l'intention de"] },
      { id: "fr-p-b1-2-c03", english: "I hope to...",           target: "J'espère" },
      { id: "fr-p-b1-2-c04", english: "I would like to...",     target: "J'aimerais" },
      { id: "fr-p-b1-2-c05", english: "If I have time, I will", target: "Si j'ai le temps je vais" },
      { id: "fr-p-b1-2-c06", english: "One day I want to...",   target: "Un jour je veux" },
      { id: "fr-p-b1-2-c07", english: "Next year",              target: "L'année prochaine" },
      { id: "fr-p-b1-2-c08", english: "In the future",          target: "À l'avenir", alternatives: ["Dans le futur"] },
      { id: "fr-p-b1-2-c09", english: "My dream is to...",      target: "Mon rêve c'est de" },
      { id: "fr-p-b1-2-c10", english: "It's not decided yet",   target: "Ce n'est pas encore décidé" },
      { id: "fr-p-b1-2-c11", english: "We'll see",              target: "On verra" },
      { id: "fr-p-b1-2-c12", english: "It's possible that...",  target: "Il est possible que" },
    ],
  },

  {
    id: "fr-p-b1-3",
    title: "B1 · Complaints & requests",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-3-c01", english: "There's a problem with", target: "Il y a un problème avec" },
      { id: "fr-p-b1-3-c02", english: "This doesn't work",      target: "Ça ne fonctionne pas" },
      { id: "fr-p-b1-3-c03", english: "I ordered...",           target: "J'ai commandé" },
      { id: "fr-p-b1-3-c04", english: "Could you...?",          target: "Pourriez-vous", alternatives: ["Tu pourrais"] },
      { id: "fr-p-b1-3-c05", english: "Would it be possible?",  target: "Ce serait possible de" },
      { id: "fr-p-b1-3-c06", english: "I'm not satisfied",      target: "Je ne suis pas satisfait" },
      { id: "fr-p-b1-3-c07", english: "I'd like a refund",      target: "Je voudrais être remboursé" },
      { id: "fr-p-b1-3-c08", english: "It's not what I expected",target: "Ce n'est pas ce que j'attendais" },
      { id: "fr-p-b1-3-c09", english: "I've been waiting for",  target: "J'attends depuis" },
      { id: "fr-p-b1-3-c10", english: "Could you fix this?",    target: "Vous pouvez régler ça" },
      { id: "fr-p-b1-3-c11", english: "Thank you for your help",target: "Merci pour votre aide" },
      { id: "fr-p-b1-3-c12", english: "Can I speak to a manager?",target: "Je peux parler au responsable" },
    ],
  },

  {
    id: "fr-p-b1-4",
    title: "B1 · Storytelling",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-4-c01", english: "So, basically...",       target: "Alors voilà" },
      { id: "fr-p-b1-4-c02", english: "At first",               target: "D'abord", alternatives: ["Au début"] },
      { id: "fr-p-b1-4-c03", english: "Then / after that",      target: "Ensuite", alternatives: ["Après"] },
      { id: "fr-p-b1-4-c04", english: "Finally / in the end",   target: "Finalement", alternatives: ["À la fin"] },
      { id: "fr-p-b1-4-c05", english: "Suddenly",               target: "Tout à coup", alternatives: ["Soudain"] },
      { id: "fr-p-b1-4-c06", english: "At the same time",       target: "En même temps" },
      { id: "fr-p-b1-4-c07", english: "I was telling myself...",target: "Je me disais que" },
      { id: "fr-p-b1-4-c08", english: "Can you believe it?",    target: "Tu y crois toi" },
      { id: "fr-p-b1-4-c09", english: "Turns out...",           target: "Il s'avère que", alternatives: ["Du coup"] },
      { id: "fr-p-b1-4-c10", english: "Long story short",       target: "Bref" },
      { id: "fr-p-b1-4-c11", english: "The best part is...",    target: "Le mieux c'est que" },
      { id: "fr-p-b1-4-c12", english: "I couldn't believe it",  target: "Je n'en revenais pas" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// ARABIC
// ─────────────────────────────────────────────────────────────────────────────

export const arabicVocabularyLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-v-a1-1",
    title: "A1 · Greetings & social basics",
    cefr: "A1",
    cards: [
      { id: "arv001", english: "Peace be upon you (universal greeting)", arabic: "السلام عليكم", target: "السلام عليكم", transliteration: "as-salāmu ʿalaykum", alternatives: ["سلام", "مرحبا"] },
      { id: "arv002", english: "And upon you peace (response)", arabic: "وعليكم السلام", target: "وعليكم السلام", transliteration: "wa-ʿalaykumu s-salām" },
      { id: "arv003", english: "Hello / Hi (informal)", arabic: "مرحبا", target: "مرحبا", transliteration: "marḥaban", alternatives: ["أهلاً", "هلا"] },
      { id: "arv004", english: "Welcome (response)", arabic: "أهلاً وسهلاً", target: "أهلاً وسهلاً", transliteration: "ahlan wa-sahlan", alternatives: ["أهلاً"] },
      { id: "arv005", english: "Good morning", arabic: "صباح الخير", target: "صباح الخير", transliteration: "ṣabāḥ al-khayr" },
      { id: "arv006", english: "Good morning (response)", arabic: "صباح النور", target: "صباح النور", transliteration: "ṣabāḥ an-nūr" },
      { id: "arv007", english: "Good evening", arabic: "مساء الخير", target: "مساء الخير", transliteration: "masāʾ al-khayr" },
      { id: "arv008", english: "Good evening (response)", arabic: "مساء النور", target: "مساء النور", transliteration: "masāʾ an-nūr" },
      { id: "arv009", english: "Good night", arabic: "تصبح على خير", target: "تصبح على خير", transliteration: "tuṣbiḥ ʿalā khayr", alternatives: ["تصبحون على خير"] },
      { id: "arv010", english: "Goodbye", arabic: "مع السلامة", target: "مع السلامة", transliteration: "maʿa s-salāma", alternatives: ["وداعاً", "إلى اللقاء"] },
      { id: "arv011", english: "Please", arabic: "من فضلك", target: "من فضلك", transliteration: "min faḍlak", alternatives: ["لو سمحت", "أرجوك"] },
      { id: "arv012", english: "Thank you", arabic: "شكراً", target: "شكراً", transliteration: "shukran" },
      { id: "arv013", english: "Thank you very much", arabic: "شكراً جزيلاً", target: "شكراً جزيلاً", transliteration: "shukran jazīlan" },
      { id: "arv014", english: "You're welcome", arabic: "عفواً", target: "عفواً", transliteration: "ʿafwan", alternatives: ["على الرحب والسعة", "بكل سرور"] },
      { id: "arv015", english: "Sorry", arabic: "آسف", target: "آسف", transliteration: "āsif", alternatives: ["آسفة", "أنا آسف"] },
      { id: "arv016", english: "Excuse me (to get attention)", arabic: "عفواً", target: "عفواً", transliteration: "ʿafwan", alternatives: ["لو سمحت"] },
      { id: "arv017", english: "Yes", arabic: "نعم", target: "نعم", transliteration: "naʿam", alternatives: ["أيوه", "آه", "أجل"] },
      { id: "arv018", english: "No", arabic: "لا", target: "لا", transliteration: "lā" },
      { id: "arv019", english: "OK / Alright", arabic: "حسناً", target: "حسناً", transliteration: "ḥasanan", alternatives: ["تمام", "أوكي", "ماشي"] },
      { id: "arv020", english: "God willing (used constantly)", arabic: "إن شاء الله", target: "إن شاء الله", transliteration: "in shāʾa llāh", alternatives: ["إنشالله"] },
    ],
  },

  {
    id: "ar-v-a1-2",
    title: "A1 · Numbers & time",
    cefr: "A1",
    cards: [
      { id: "arv021", english: "Zero", arabic: "صفر", target: "صفر", transliteration: "ṣifr" },
      { id: "arv022", english: "One", arabic: "واحد", target: "واحد", transliteration: "wāḥid", alternatives: ["واحدة"] },
      { id: "arv023", english: "Two", arabic: "اثنان", target: "اثنان", transliteration: "ithnān", alternatives: ["اثنين"] },
      { id: "arv024", english: "Three", arabic: "ثلاثة", target: "ثلاثة", transliteration: "thalātha" },
      { id: "arv025", english: "Four", arabic: "أربعة", target: "أربعة", transliteration: "arbaʿa" },
      { id: "arv026", english: "Five", arabic: "خمسة", target: "خمسة", transliteration: "khamsa" },
      { id: "arv027", english: "Six", arabic: "ستة", target: "ستة", transliteration: "sitta" },
      { id: "arv028", english: "Seven", arabic: "سبعة", target: "سبعة", transliteration: "sabʿa" },
      { id: "arv029", english: "Eight", arabic: "ثمانية", target: "ثمانية", transliteration: "thamāniya" },
      { id: "arv030", english: "Nine", arabic: "تسعة", target: "تسعة", transliteration: "tisʿa" },
      { id: "arv031", english: "Ten", arabic: "عشرة", target: "عشرة", transliteration: "ʿashara" },
      { id: "arv032", english: "Twenty", arabic: "عشرون", target: "عشرون", transliteration: "ʿishrūn", alternatives: ["عشرين"] },
      { id: "arv033", english: "Fifty", arabic: "خمسون", target: "خمسون", transliteration: "khamsūn", alternatives: ["خمسين"] },
      { id: "arv034", english: "One hundred", arabic: "مئة", target: "مئة", transliteration: "miʾa", alternatives: ["مية"] },
      { id: "arv035", english: "One thousand", arabic: "ألف", target: "ألف", transliteration: "alf" },
      { id: "arv036", english: "What time is it?", arabic: "كم الساعة؟", target: "كم الساعة", transliteration: "kam as-sāʿa" },
      { id: "arv037", english: "It is three o'clock", arabic: "الساعة الثالثة", target: "الساعة الثالثة", transliteration: "as-sāʿa ath-thālitha" },
      { id: "arv038", english: "In the morning", arabic: "في الصباح", target: "في الصباح", transliteration: "fī aṣ-ṣabāḥ", alternatives: ["صباحاً"] },
      { id: "arv039", english: "In the evening", arabic: "في المساء", target: "في المساء", transliteration: "fī al-masāʾ", alternatives: ["مساءً"] },
      { id: "arv040", english: "At noon", arabic: "في الظهيرة", target: "في الظهيرة", transliteration: "fī aẓ-ẓahīra", alternatives: ["الظهر"] },
    ],
  },

  {
    id: "ar-v-a1-3",
    title: "A1 · Days, months & time words",
    cefr: "A1",
    cards: [
      { id: "arv041", english: "Sunday", arabic: "الأحد", target: "الأحد", transliteration: "al-aḥad" },
      { id: "arv042", english: "Monday", arabic: "الاثنين", target: "الاثنين", transliteration: "al-ithnayn" },
      { id: "arv043", english: "Tuesday", arabic: "الثلاثاء", target: "الثلاثاء", transliteration: "ath-thulāthāʾ" },
      { id: "arv044", english: "Wednesday", arabic: "الأربعاء", target: "الأربعاء", transliteration: "al-arbiʿāʾ" },
      { id: "arv045", english: "Thursday", arabic: "الخميس", target: "الخميس", transliteration: "al-khamīs" },
      { id: "arv046", english: "Friday", arabic: "الجمعة", target: "الجمعة", transliteration: "al-jumuʿa" },
      { id: "arv047", english: "Saturday", arabic: "السبت", target: "السبت", transliteration: "as-sabt" },
      { id: "arv048", english: "Today", arabic: "اليوم", target: "اليوم", transliteration: "al-yawm" },
      { id: "arv049", english: "Tomorrow", arabic: "غداً", target: "غداً", transliteration: "ghadan", alternatives: ["بكرة", "بكره"] },
      { id: "arv050", english: "Yesterday", arabic: "أمس", target: "أمس", transliteration: "ams", alternatives: ["امبارح"] },
      { id: "arv051", english: "Now", arabic: "الآن", target: "الآن", transliteration: "al-ān", alternatives: ["دلوقتي", "هلأ"] },
      { id: "arv052", english: "Later", arabic: "لاحقاً", target: "لاحقاً", transliteration: "lāḥiqan", alternatives: ["بعدين"] },
      { id: "arv053", english: "Always", arabic: "دائماً", target: "دائماً", transliteration: "dāʾiman" },
      { id: "arv054", english: "Never", arabic: "أبداً", target: "أبداً", transliteration: "abadan" },
      { id: "arv055", english: "Sometimes", arabic: "أحياناً", target: "أحياناً", transliteration: "aḥyānan" },
      { id: "arv056", english: "This week", arabic: "هذا الأسبوع", target: "هذا الأسبوع", transliteration: "hādhā al-usbūʿ" },
      { id: "arv057", english: "Next week", arabic: "الأسبوع القادم", target: "الأسبوع القادم", transliteration: "al-usbūʿ al-qādim", alternatives: ["الأسبوع الجاي"] },
      { id: "arv058", english: "Last week", arabic: "الأسبوع الماضي", target: "الأسبوع الماضي", transliteration: "al-usbūʿ al-māḍī" },
      { id: "arv059", english: "January", arabic: "يناير", target: "يناير", transliteration: "yanāyir", alternatives: ["كانون الثاني"] },
      { id: "arv060", english: "Ramadan (holy month)", arabic: "رمضان", target: "رمضان", transliteration: "ramaḍān" },
    ],
  },

  {
    id: "ar-v-a1-4",
    title: "A1 · Core verbs (15 you can't live without)",
    cefr: "A1",
    cards: [
      { id: "arv061", english: "To be (he was)", arabic: "كان", target: "كان", transliteration: "kāna" },
      { id: "arv062", english: "To have (he had)", arabic: "كان عنده", target: "كان عنده", transliteration: "kāna ʿindahu", alternatives: ["لديه"] },
      { id: "arv063", english: "To go (he went)", arabic: "ذهب", target: "ذهب", transliteration: "dhahaba", alternatives: ["راح"] },
      { id: "arv064", english: "To do / make (he did)", arabic: "فعل", target: "فعل", transliteration: "faʿala", alternatives: ["عمل"] },
      { id: "arv065", english: "To want (he wanted)", arabic: "أراد", target: "أراد", transliteration: "arāda", alternatives: ["عاوز", "بدّه"] },
      { id: "arv066", english: "To be able to (he could)", arabic: "استطاع", target: "استطاع", transliteration: "istaṭāʿa", alternatives: ["قدر"] },
      { id: "arv067", english: "To know (he knew)", arabic: "عرف", target: "عرف", transliteration: "ʿarafa" },
      { id: "arv068", english: "To come (he came)", arabic: "جاء", target: "جاء", transliteration: "jāʾa", alternatives: ["أجى", "إجى"] },
      { id: "arv069", english: "To see (he saw)", arabic: "رأى", target: "رأى", transliteration: "raʾā", alternatives: ["شاف"] },
      { id: "arv070", english: "To speak (he spoke)", arabic: "تكلّم", target: "تكلّم", transliteration: "takallama", alternatives: ["حكى"] },
      { id: "arv071", english: "To eat (he ate)", arabic: "أكل", target: "أكل", transliteration: "akala" },
      { id: "arv072", english: "To drink (he drank)", arabic: "شرب", target: "شرب", transliteration: "shariba" },
      { id: "arv073", english: "To live / reside (he lived)", arabic: "سكن", target: "سكن", transliteration: "sakana", alternatives: ["عاش"] },
      { id: "arv074", english: "To work (he worked)", arabic: "عمل", target: "عمل", transliteration: "ʿamila", alternatives: ["اشتغل"] },
      { id: "arv075", english: "To like / love (he liked)", arabic: "أحبّ", target: "أحبّ", transliteration: "aḥabba", alternatives: ["حبّ"] },
    ],
  },

  {
    id: "ar-v-a1-5",
    title: "A1 · People & family",
    cefr: "A1",
    cards: [
      { id: "arv076", english: "A man", arabic: "رجل", target: "رجل", transliteration: "rajul" },
      { id: "arv077", english: "A woman", arabic: "امرأة", target: "امرأة", transliteration: "imraʾa", alternatives: ["ست"] },
      { id: "arv078", english: "A child", arabic: "طفل", target: "طفل", transliteration: "ṭifl" },
      { id: "arv079", english: "A boy", arabic: "ولد", target: "ولد", transliteration: "walad" },
      { id: "arv080", english: "A girl", arabic: "بنت", target: "بنت", transliteration: "bint" },
      { id: "arv081", english: "A friend (male)", arabic: "صديق", target: "صديق", transliteration: "ṣadīq", alternatives: ["صاحب"] },
      { id: "arv082", english: "A friend (female)", arabic: "صديقة", target: "صديقة", transliteration: "ṣadīqa", alternatives: ["صاحبة"] },
      { id: "arv083", english: "The father", arabic: "الأب", target: "الأب", transliteration: "al-ab", alternatives: ["البابا", "الوالد"] },
      { id: "arv084", english: "The mother", arabic: "الأم", target: "الأم", transliteration: "al-umm", alternatives: ["الماما", "الوالدة"] },
      { id: "arv085", english: "The brother", arabic: "الأخ", target: "الأخ", transliteration: "al-akh" },
      { id: "arv086", english: "The sister", arabic: "الأخت", target: "الأخت", transliteration: "al-ukht" },
      { id: "arv087", english: "The son", arabic: "الابن", target: "الابن", transliteration: "al-ibn" },
      { id: "arv088", english: "The daughter", arabic: "البنت", target: "البنت", transliteration: "al-bint", alternatives: ["الابنة"] },
      { id: "arv089", english: "The husband", arabic: "الزوج", target: "الزوج", transliteration: "az-zawj" },
      { id: "arv090", english: "The wife", arabic: "الزوجة", target: "الزوجة", transliteration: "az-zawja" },
      { id: "arv091", english: "The family", arabic: "العائلة", target: "العائلة", transliteration: "al-ʿāʾila", alternatives: ["الأسرة"] },
      { id: "arv092", english: "The grandfather", arabic: "الجد", target: "الجد", transliteration: "al-jadd" },
      { id: "arv093", english: "The grandmother", arabic: "الجدة", target: "الجدة", transliteration: "al-jadda" },
    ],
  },

  {
    id: "ar-v-a1-6",
    title: "A1 · Food & drink",
    cefr: "A1",
    cards: [
      { id: "arv094", english: "Water", arabic: "ماء", target: "ماء", transliteration: "māʾ", alternatives: ["مياه"] },
      { id: "arv095", english: "Coffee", arabic: "قهوة", target: "قهوة", transliteration: "qahwa" },
      { id: "arv096", english: "Tea", arabic: "شاي", target: "شاي", transliteration: "shāy" },
      { id: "arv097", english: "Juice", arabic: "عصير", target: "عصير", transliteration: "ʿaṣīr" },
      { id: "arv098", english: "Milk", arabic: "حليب", target: "حليب", transliteration: "ḥalīb", alternatives: ["لبن"] },
      { id: "arv099", english: "Bread", arabic: "خبز", target: "خبز", transliteration: "khubz", alternatives: ["عيش"] },
      { id: "arv100", english: "Rice", arabic: "أرز", target: "أرز", transliteration: "aruzz", alternatives: ["رز"] },
      { id: "arv101", english: "Meat", arabic: "لحم", target: "لحم", transliteration: "laḥm" },
      { id: "arv102", english: "Chicken", arabic: "دجاج", target: "دجاج", transliteration: "dajāj" },
      { id: "arv103", english: "Fish", arabic: "سمك", target: "سمك", transliteration: "samak" },
      { id: "arv104", english: "Vegetables", arabic: "خضروات", target: "خضروات", transliteration: "khuḍruwāt", alternatives: ["خضار"] },
      { id: "arv105", english: "Fruit", arabic: "فاكهة", target: "فاكهة", transliteration: "fākiha", alternatives: ["فواكه"] },
      { id: "arv106", english: "Sugar", arabic: "سكر", target: "سكر", transliteration: "sukkar" },
      { id: "arv107", english: "Salt", arabic: "ملح", target: "ملح", transliteration: "milḥ" },
      { id: "arv108", english: "The bill", arabic: "الحساب", target: "الحساب", transliteration: "al-ḥisāb", alternatives: ["الفاتورة"] },
      { id: "arv109", english: "I am hungry", arabic: "أنا جائع", target: "أنا جائع", transliteration: "anā jāʾiʿ", alternatives: ["أنا جعان"] },
      { id: "arv110", english: "I am thirsty", arabic: "أنا عطشان", target: "أنا عطشان", transliteration: "anā ʿaṭshān" },
      { id: "arv111", english: "Delicious", arabic: "لذيذ", target: "لذيذ", transliteration: "ladhīdh", alternatives: ["طيب", "تمام"] },
    ],
  },

  {
    id: "ar-v-a1-7",
    title: "A1 · Places & getting around",
    cefr: "A1",
    cards: [
      { id: "arv112", english: "The city", arabic: "المدينة", target: "المدينة", transliteration: "al-madīna" },
      { id: "arv113", english: "The street", arabic: "الشارع", target: "الشارع", transliteration: "ash-shāriʿ" },
      { id: "arv114", english: "The house", arabic: "البيت", target: "البيت", transliteration: "al-bayt", alternatives: ["المنزل"] },
      { id: "arv115", english: "The mosque", arabic: "المسجد", target: "المسجد", transliteration: "al-masjid" },
      { id: "arv116", english: "The hospital", arabic: "المستشفى", target: "المستشفى", transliteration: "al-mustashfā" },
      { id: "arv117", english: "The pharmacy", arabic: "الصيدلية", target: "الصيدلية", transliteration: "aṣ-ṣaydaliyya" },
      { id: "arv118", english: "The bank", arabic: "البنك", target: "البنك", transliteration: "al-bank" },
      { id: "arv119", english: "The market / souk", arabic: "السوق", target: "السوق", transliteration: "as-sūq" },
      { id: "arv120", english: "The restaurant", arabic: "المطعم", target: "المطعم", transliteration: "al-maṭʿam" },
      { id: "arv121", english: "The hotel", arabic: "الفندق", target: "الفندق", transliteration: "al-funduq" },
      { id: "arv122", english: "The airport", arabic: "المطار", target: "المطار", transliteration: "al-maṭār" },
      { id: "arv123", english: "On the right", arabic: "على اليمين", target: "على اليمين", transliteration: "ʿalā l-yamīn", alternatives: ["يمين"] },
      { id: "arv124", english: "On the left", arabic: "على اليسار", target: "على اليسار", transliteration: "ʿalā l-yasār", alternatives: ["شمال", "يسار"] },
      { id: "arv125", english: "Straight ahead", arabic: "على طول", target: "على طول", transliteration: "ʿalā ṭūl", alternatives: ["مباشرة"] },
      { id: "arv126", english: "Near / close", arabic: "قريب", target: "قريب", transliteration: "qarīb" },
      { id: "arv127", english: "Far", arabic: "بعيد", target: "بعيد", transliteration: "baʿīd" },
      { id: "arv128", english: "The toilet / bathroom", arabic: "الحمام", target: "الحمام", transliteration: "al-ḥammām", alternatives: ["التواليت", "دورة المياه"] },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-v-a2-1",
    title: "A2 · Everyday adjectives",
    cefr: "A2",
    cards: [
      { id: "arv129", english: "Good", arabic: "جيد", target: "جيد", transliteration: "jayyid", alternatives: ["كويس", "مليح"] },
      { id: "arv130", english: "Bad", arabic: "سيئ", target: "سيئ", transliteration: "sayyi'", alternatives: ["وحش", "مش كويس"] },
      { id: "arv131", english: "Big / large", arabic: "كبير", target: "كبير", transliteration: "kabīr", alternatives: ["كبيرة"] },
      { id: "arv132", english: "Small / little", arabic: "صغير", target: "صغير", transliteration: "ṣaghīr", alternatives: ["صغيرة"] },
      { id: "arv133", english: "New", arabic: "جديد", target: "جديد", transliteration: "jadīd", alternatives: ["جديدة"] },
      { id: "arv134", english: "Old (object)", arabic: "قديم", target: "قديم", transliteration: "qadīm", alternatives: ["قديمة"] },
      { id: "arv135", english: "Old (person)", arabic: "كبير في السن", target: "كبير في السن", transliteration: "kabīr fī s-sinn" },
      { id: "arv136", english: "Beautiful", arabic: "جميل", target: "جميل", transliteration: "jamīl", alternatives: ["جميلة", "حلو", "حلوة"] },
      { id: "arv137", english: "Happy", arabic: "سعيد", target: "سعيد", transliteration: "saʿīd", alternatives: ["سعيدة", "مبسوط"] },
      { id: "arv138", english: "Sad", arabic: "حزين", target: "حزين", transliteration: "ḥazīn", alternatives: ["حزينة", "زعلان"] },
      { id: "arv139", english: "Tired", arabic: "تعبان", target: "تعبان", transliteration: "taʿbān", alternatives: ["متعب"] },
      { id: "arv140", english: "Busy", arabic: "مشغول", target: "مشغول", transliteration: "mashghūl", alternatives: ["مشغولة"] },
      { id: "arv141", english: "Easy", arabic: "سهل", target: "سهل", transliteration: "sahl", alternatives: ["سهلة", "بسيط"] },
      { id: "arv142", english: "Difficult", arabic: "صعب", target: "صعب", transliteration: "ṣaʿb", alternatives: ["صعبة"] },
      { id: "arv143", english: "Expensive", arabic: "غالي", target: "غالي", transliteration: "ghālī", alternatives: ["غاليه"] },
      { id: "arv144", english: "Cheap / affordable", arabic: "رخيص", target: "رخيص", transliteration: "rakhīṣ", alternatives: ["رخيصة", "بسعر كويس"] },
      { id: "arv145", english: "Hot", arabic: "حار", target: "حار", transliteration: "ḥārr", alternatives: ["سخن"] },
      { id: "arv146", english: "Cold", arabic: "بارد", target: "بارد", transliteration: "bārid", alternatives: ["بردان"] },
      { id: "arv147", english: "Clean", arabic: "نظيف", target: "نظيف", transliteration: "naẓīf", alternatives: ["نظيفة"] },
      { id: "arv148", english: "Fast / quick", arabic: "سريع", target: "سريع", transliteration: "sarīʿ", alternatives: ["سريعة"] },
      { id: "arv149", english: "Slow", arabic: "بطيء", target: "بطيء", transliteration: "baṭīʾ", alternatives: ["بطيئة"] },
      { id: "arv150", english: "Important", arabic: "مهم", target: "مهم", transliteration: "muhimm", alternatives: ["مهمة"] },
    ],
  },

  {
    id: "ar-v-a2-2",
    title: "A2 · Daily routine verbs",
    cefr: "A2",
    cards: [
      { id: "arv151", english: "To wake up", arabic: "صحا", target: "صحا", transliteration: "ṣaḥā", alternatives: ["صحى", "استيقظ"] },
      { id: "arv152", english: "To get up", arabic: "نهض", target: "نهض", transliteration: "nahaḍa", alternatives: ["قام"] },
      { id: "arv153", english: "To shower / bathe", arabic: "اغتسل", target: "اغتسل", transliteration: "ightasala", alternatives: ["اتحمّم"] },
      { id: "arv154", english: "To get dressed", arabic: "لبس", target: "لبس", transliteration: "labisa" },
      { id: "arv155", english: "To have breakfast", arabic: "تناول الفطور", target: "تناول الفطور", transliteration: "tanāwala l-fuṭūr", alternatives: ["فطر", "اتفطر"] },
      { id: "arv156", english: "To study", arabic: "درس", target: "درس", transliteration: "darasa" },
      { id: "arv157", english: "To read", arabic: "قرأ", target: "قرأ", transliteration: "qaraʾa" },
      { id: "arv158", english: "To write", arabic: "كتب", target: "كتب", transliteration: "kataba" },
      { id: "arv159", english: "To cook", arabic: "طبخ", target: "طبخ", transliteration: "ṭabakha", alternatives: ["حضّر الأكل"] },
      { id: "arv160", english: "To watch TV", arabic: "شاهد التلفزيون", target: "شاهد التلفزيون", transliteration: "shāhada t-tilfiziyūn", alternatives: ["اتفرّج"] },
      { id: "arv161", english: "To sleep", arabic: "نام", target: "نام", transliteration: "nāma" },
      { id: "arv162", english: "To go to bed", arabic: "ذهب للنوم", target: "ذهب للنوم", transliteration: "dhahaba li-n-nawm", alternatives: ["راح ينام"] },
      { id: "arv163", english: "To call (on phone)", arabic: "اتصل", target: "اتصل", transliteration: "ittaṣala", alternatives: ["كلّم"] },
      { id: "arv164", english: "To pray", arabic: "صلّى", target: "صلّى", transliteration: "ṣallā" },
      { id: "arv165", english: "To travel", arabic: "سافر", target: "سافر", transliteration: "sāfara" },
    ],
  },

  {
    id: "ar-v-a2-3",
    title: "A2 · Shopping & money",
    cefr: "A2",
    cards: [
      { id: "arv166", english: "To buy", arabic: "اشترى", target: "اشترى", transliteration: "ishtarā" },
      { id: "arv167", english: "To sell", arabic: "باع", target: "باع", transliteration: "bāʿa" },
      { id: "arv168", english: "To pay", arabic: "دفع", target: "دفع", transliteration: "dafaʿa" },
      { id: "arv169", english: "The price", arabic: "السعر", target: "السعر", transliteration: "as-siʿr", alternatives: ["الثمن"] },
      { id: "arv170", english: "Cash", arabic: "نقداً", target: "نقداً", transliteration: "naqdan", alternatives: ["كاش", "فلوس"] },
      { id: "arv171", english: "Card payment", arabic: "بطاقة", target: "بطاقة", transliteration: "biṭāqa", alternatives: ["كارت"] },
      { id: "arv172", english: "A receipt", arabic: "إيصال", target: "إيصال", transliteration: "īṣāl", alternatives: ["فاتورة"] },
      { id: "arv173", english: "Discount / offer", arabic: "خصم", target: "خصم", transliteration: "khaṣm", alternatives: ["تخفيض"] },
      { id: "arv174", english: "The size", arabic: "المقاس", target: "المقاس", transliteration: "al-maqās", alternatives: ["الحجم"] },
      { id: "arv175", english: "Too expensive", arabic: "غالي جداً", target: "غالي جداً", transliteration: "ghālī jiddan" },
      { id: "arv176", english: "I'll take it", arabic: "سآخذه", target: "سآخذه", transliteration: "sa-ākhudhuhu", alternatives: ["هاخده", "بآخده"] },
      { id: "arv177", english: "The change (money)", arabic: "الباقي", target: "الباقي", transliteration: "al-bāqī", alternatives: ["الفكّة"] },
      { id: "arv178", english: "Can you lower the price?", arabic: "تنزّل السعر؟", target: "تنزّل السعر", transliteration: "tunazzil as-siʿr", alternatives: ["ما تحطّ سعر أحسن"] },
    ],
  },

  {
    id: "ar-v-a2-4",
    title: "A2 · Transport & travel",
    cefr: "A2",
    cards: [
      { id: "arv179", english: "The car", arabic: "السيارة", target: "السيارة", transliteration: "as-sayyāra", alternatives: ["العربية"] },
      { id: "arv180", english: "The bus", arabic: "الحافلة", target: "الحافلة", transliteration: "al-ḥāfila", alternatives: ["الأتوبيس", "الباص"] },
      { id: "arv181", english: "The metro / subway", arabic: "المترو", target: "المترو", transliteration: "al-mitrū" },
      { id: "arv182", english: "The taxi", arabic: "سيارة الأجرة", target: "سيارة الأجرة", transliteration: "sayyārat al-ujra", alternatives: ["التاكسي"] },
      { id: "arv183", english: "The plane", arabic: "الطائرة", target: "الطائرة", transliteration: "aṭ-ṭāʾira" },
      { id: "arv184", english: "The train", arabic: "القطار", target: "القطار", transliteration: "al-qiṭār" },
      { id: "arv185", english: "A ticket", arabic: "تذكرة", target: "تذكرة", transliteration: "tadhkira" },
      { id: "arv186", english: "The departure", arabic: "المغادرة", target: "المغادرة", transliteration: "al-mughādara", alternatives: ["الإقلاع"] },
      { id: "arv187", english: "The arrival", arabic: "الوصول", target: "الوصول", transliteration: "al-wuṣūl" },
      { id: "arv188", english: "On time", arabic: "في الوقت المحدد", target: "في الوقت المحدد", transliteration: "fī l-waqt al-muḥaddad", alternatives: ["بالوقت"] },
      { id: "arv189", english: "Late", arabic: "متأخر", target: "متأخر", transliteration: "mutaʾakhkhir", alternatives: ["أخّرت"] },
      { id: "arv190", english: "The luggage", arabic: "الأمتعة", target: "الأمتعة", transliteration: "al-amtiʿa", alternatives: ["الشنط"] },
      { id: "arv191", english: "The passport", arabic: "جواز السفر", target: "جواز السفر", transliteration: "jawāz as-safar", alternatives: ["الباسبور"] },
      { id: "arv192", english: "The visa", arabic: "التأشيرة", target: "التأشيرة", transliteration: "at-taʾshīra", alternatives: ["الفيزا"] },
    ],
  },

  {
    id: "ar-v-a2-5",
    title: "A2 · Health & body",
    cefr: "A2",
    cards: [
      { id: "arv193", english: "I have a headache", arabic: "عندي صداع", target: "عندي صداع", transliteration: "ʿindī ṣudāʿ", alternatives: ["رأسي بيوجعني"] },
      { id: "arv194", english: "I have a stomach ache", arabic: "بطني تؤلمني", target: "بطني تؤلمني", transliteration: "baṭnī tuʾlimunī", alternatives: ["عندي ألم في البطن"] },
      { id: "arv195", english: "I feel sick", arabic: "أنا مريض", target: "أنا مريض", transliteration: "anā marīḍ", alternatives: ["أنا تعبان"] },
      { id: "arv196", english: "I have a fever", arabic: "عندي حرارة", target: "عندي حرارة", transliteration: "ʿindī ḥarāra", alternatives: ["عندي سخونة"] },
      { id: "arv197", english: "The doctor", arabic: "الطبيب", target: "الطبيب", transliteration: "aṭ-ṭabīb", alternatives: ["الدكتور"] },
      { id: "arv198", english: "A medicine", arabic: "دواء", target: "دواء", transliteration: "dawāʾ" },
      { id: "arv199", english: "An appointment", arabic: "موعد", target: "موعد", transliteration: "mawʿid" },
      { id: "arv200", english: "The head", arabic: "الرأس", target: "الرأس", transliteration: "ar-raʾs" },
      { id: "arv201", english: "The back", arabic: "الظهر", target: "الظهر", transliteration: "aẓ-ẓahr" },
      { id: "arv202", english: "The stomach", arabic: "البطن", target: "البطن", transliteration: "al-baṭn", alternatives: ["المعدة"] },
      { id: "arv203", english: "The arm", arabic: "الذراع", target: "الذراع", transliteration: "adh-dhirāʿ", alternatives: ["الإيد"] },
      { id: "arv204", english: "The leg", arabic: "الساق", target: "الساق", transliteration: "as-sāq", alternatives: ["الرِّجل"] },
      { id: "arv205", english: "To rest", arabic: "استراح", target: "استراح", transliteration: "istārāḥa", alternatives: ["ارتاح"] },
      { id: "arv206", english: "Allergic to", arabic: "عندي حساسية من", target: "عندي حساسية من", transliteration: "ʿindī ḥasāsiyya min" },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-v-b1-1",
    title: "B1 · Conversation connectors",
    cefr: "B1",
    cards: [
      { id: "arv207", english: "I mean / you know (used constantly)", arabic: "يعني", target: "يعني", transliteration: "yaʿnī" },
      { id: "arv208", english: "So / therefore (spoken)", arabic: "إذن", target: "إذن", transliteration: "idhan", alternatives: ["يعني", "فـ"] },
      { id: "arv209", english: "Actually / in fact", arabic: "في الحقيقة", target: "في الحقيقة", transliteration: "fī l-ḥaqīqa", alternatives: ["أصلاً", "بالحقيقة"] },
      { id: "arv210", english: "Of course", arabic: "بالطبع", target: "بالطبع", transliteration: "biṭ-ṭabʿ", alternatives: ["طبعاً", "أكيد"] },
      { id: "arv211", english: "Certainly / definitely", arabic: "بالتأكيد", target: "بالتأكيد", transliteration: "bit-taʾkīd", alternatives: ["أكيد"] },
      { id: "arv212", english: "However / but", arabic: "لكن", target: "لكن", transliteration: "lākin", alternatives: ["بس", "ولكن"] },
      { id: "arv213", english: "Also / in addition", arabic: "أيضاً", target: "أيضاً", transliteration: "ayḍan", alternatives: ["كمان", "كذلك"] },
      { id: "arv214", english: "For example", arabic: "مثلاً", target: "مثلاً", transliteration: "mathalan", alternatives: ["على سبيل المثال"] },
      { id: "arv215", english: "That's why / so", arabic: "لهذا", target: "لهذا", transliteration: "li-hādhā", alternatives: ["عشان كده", "لهذا السبب"] },
      { id: "arv216", english: "In my opinion", arabic: "في رأيي", target: "في رأيي", transliteration: "fī raʾyī", alternatives: ["برأيي", "من وجهة نظري"] },
      { id: "arv217", english: "I think that", arabic: "أعتقد أن", target: "أعتقد أن", transliteration: "aʿtaqidu an", alternatives: ["أظن أن", "أنا شايف"] },
      { id: "arv218", english: "It depends", arabic: "يعتمد", target: "يعتمد", transliteration: "yaʿtamid", alternatives: ["حسب الظروف", "على حسب"] },
      { id: "arv219", english: "Not really / not exactly", arabic: "ليس تماماً", target: "ليس تماماً", transliteration: "laysa tamāman", alternatives: ["مش أوي", "مش بالضبط"] },
      { id: "arv220", english: "Exactly / precisely", arabic: "بالضبط", target: "بالضبط", transliteration: "biḍ-ḍabṭ", alternatives: ["تماماً"] },
      { id: "arv221", english: "More or less", arabic: "تقريباً", target: "تقريباً", transliteration: "taqrīban", alternatives: ["نوعاً ما"] },
      { id: "arv222", english: "In general", arabic: "بشكل عام", target: "بشكل عام", transliteration: "bi-shakl ʿāmm", alternatives: ["عموماً"] },
      { id: "arv223", english: "To be honest", arabic: "بصراحة", target: "بصراحة", transliteration: "bi-ṣarāḥa", alternatives: ["بكل صدق"] },
      { id: "arv224", english: "At the same time", arabic: "في نفس الوقت", target: "في نفس الوقت", transliteration: "fī nafs al-waqt" },
      { id: "arv225", english: "Above all / especially", arabic: "خاصةً", target: "خاصةً", transliteration: "khāṣṣatan", alternatives: ["بالأخص", "وخصوصاً"] },
      { id: "arv226", english: "Unfortunately / what a pity", arabic: "للأسف", target: "للأسف", transliteration: "lil-asaf", alternatives: ["يا حسرة"] },
    ],
  },

  {
    id: "ar-v-b1-2",
    title: "B1 · Work & professional life",
    cefr: "B1",
    cards: [
      { id: "arv227", english: "A job / position", arabic: "وظيفة", target: "وظيفة", transliteration: "waẓīfa", alternatives: ["شغل", "عمل"] },
      { id: "arv228", english: "A company", arabic: "شركة", target: "شركة", transliteration: "sharika" },
      { id: "arv229", english: "A meeting", arabic: "اجتماع", target: "اجتماع", transliteration: "ijtimāʿ" },
      { id: "arv230", english: "A client", arabic: "عميل", target: "عميل", transliteration: "ʿamīl", alternatives: ["زبون"] },
      { id: "arv231", english: "A colleague", arabic: "زميل", target: "زميل", transliteration: "zamīl", alternatives: ["زميلة"] },
      { id: "arv232", english: "The boss / manager", arabic: "المدير", target: "المدير", transliteration: "al-mudīr", alternatives: ["المسؤول", "الرئيس"] },
      { id: "arv233", english: "A project", arabic: "مشروع", target: "مشروع", transliteration: "mashrūʿ" },
      { id: "arv234", english: "A salary", arabic: "راتب", target: "راتب", transliteration: "rātib", alternatives: ["مرتّب"] },
      { id: "arv235", english: "A deadline", arabic: "موعد نهائي", target: "موعد نهائي", transliteration: "mawʿid nihāʾī", alternatives: ["آخر موعد"] },
      { id: "arv236", english: "An interview", arabic: "مقابلة عمل", target: "مقابلة عمل", transliteration: "muqābala ʿamal", alternatives: ["انترفيو"] },
      { id: "arv237", english: "To apply for a job", arabic: "تقدّم لوظيفة", target: "تقدّم لوظيفة", transliteration: "taqaddama li-waẓīfa" },
      { id: "arv238", english: "To hire", arabic: "وظّف", target: "وظّف", transliteration: "waẓẓafa", alternatives: ["شغّل"] },
      { id: "arv239", english: "To resign", arabic: "استقال", target: "استقال", transliteration: "istaqāla" },
      { id: "arv240", english: "A contract", arabic: "عقد", target: "عقد", transliteration: "ʿaqd" },
      { id: "arv241", english: "Leave / holiday", arabic: "إجازة", target: "إجازة", transliteration: "ijāza", alternatives: ["عطلة"] },
      { id: "arv242", english: "To work remotely", arabic: "العمل عن بُعد", target: "العمل عن بُعد", transliteration: "al-ʿamal ʿan buʿd", alternatives: ["يشتغل من البيت"] },
      { id: "arv243", english: "Freelance / self-employed", arabic: "مستقل", target: "مستقل", transliteration: "mustaqill", alternatives: ["فريلانسر"] },
    ],
  },

  {
    id: "ar-v-b1-3",
    title: "B1 · Emotions & feelings",
    cefr: "B1",
    cards: [
      { id: "arv244", english: "I feel...", arabic: "أشعر بـ", target: "أشعر بـ", transliteration: "ashʿuru bi-", alternatives: ["أنا حاسس بـ"] },
      { id: "arv245", english: "Stressed", arabic: "متوتر", target: "متوتر", transliteration: "mutawattir", alternatives: ["مضغوط", "ضايق"] },
      { id: "arv246", english: "Anxious / worried", arabic: "قلق", target: "قلق", transliteration: "qaliq", alternatives: ["قلقانة", "خايف"] },
      { id: "arv247", english: "Excited / enthusiastic", arabic: "متحمّس", target: "متحمّس", transliteration: "mutaḥammis", alternatives: ["متحمّسة"] },
      { id: "arv248", english: "Disappointed", arabic: "محبط", target: "محبط", transliteration: "muḥbaṭ", alternatives: ["خايب أمله", "زعلان"] },
      { id: "arv249", english: "Surprised", arabic: "مندهش", target: "مندهش", transliteration: "mundahish", alternatives: ["متفاجئ", "مصدوم"] },
      { id: "arv250", english: "Relieved", arabic: "مرتاح", target: "مرتاح", transliteration: "murtāḥ", alternatives: ["انشرح صدره"] },
      { id: "arv251", english: "Proud", arabic: "فخور", target: "فخور", transliteration: "fakhūr", alternatives: ["معتزّ"] },
      { id: "arv252", english: "Comfortable / at ease", arabic: "مرتاح", target: "مرتاح", transliteration: "murtāḥ", alternatives: ["على راحتي"] },
      { id: "arv253", english: "Bored", arabic: "ملول", target: "ملول", transliteration: "malūl", alternatives: ["زهقان", "مللت"] },
      { id: "arv254", english: "Angry", arabic: "غاضب", target: "غاضب", transliteration: "ghāḍib", alternatives: ["زعلان", "معصّب"] },
      { id: "arv255", english: "To miss (someone)", arabic: "اشتاق", target: "اشتاق", transliteration: "ishtāqa", alternatives: ["وحشتني", "اشتقت لك"] },
      { id: "arv256", english: "To love / adore", arabic: "أحبّ", target: "أحبّ", transliteration: "uḥibbu", alternatives: ["عشق", "بحبّ"] },
      { id: "arv257", english: "To hate / dislike", arabic: "يكره", target: "يكره", transliteration: "yakrahu", alternatives: ["ما بحبّش", "بيكره"] },
    ],
  },

  {
    id: "ar-v-b1-4",
    title: "B1 · Technology & modern life",
    cefr: "B1",
    cards: [
      { id: "arv258", english: "A smartphone", arabic: "هاتف ذكي", target: "هاتف ذكي", transliteration: "hātif dhakī", alternatives: ["موبايل", "تلفون"] },
      { id: "arv259", english: "The internet", arabic: "الإنترنت", target: "الإنترنت", transliteration: "al-internet" },
      { id: "arv260", english: "Wi-Fi", arabic: "الواي فاي", target: "الواي فاي", transliteration: "al-wāy fāy", alternatives: ["وايفاي"] },
      { id: "arv261", english: "To send a message", arabic: "أرسل رسالة", target: "أرسل رسالة", transliteration: "arsala risāla", alternatives: ["بعت مسج"] },
      { id: "arv262", english: "Social media", arabic: "وسائل التواصل الاجتماعي", target: "وسائل التواصل الاجتماعي", transliteration: "wasāʾil at-tawāṣul al-ijtimāʿī", alternatives: ["السوشيال ميديا"] },
      { id: "arv263", english: "To download", arabic: "نزّل", target: "نزّل", transliteration: "nazzala", alternatives: ["حمّل"] },
      { id: "arv264", english: "An app", arabic: "تطبيق", target: "تطبيق", transliteration: "taṭbīq", alternatives: ["أبلكيشن"] },
      { id: "arv265", english: "A computer", arabic: "حاسوب", target: "حاسوب", transliteration: "ḥāsūb", alternatives: ["كمبيوتر", "لابتوب"] },
      { id: "arv266", english: "A password", arabic: "كلمة المرور", target: "كلمة المرور", transliteration: "kalimat al-murūr", alternatives: ["باسورد"] },
      { id: "arv267", english: "To charge (the phone)", arabic: "شحن الهاتف", target: "شحن الهاتف", transliteration: "shaḥn al-hātif", alternatives: ["يشحن الموبايل"] },
      { id: "arv268", english: "It doesn't work", arabic: "لا يعمل", target: "لا يعمل", transliteration: "lā yaʿmal", alternatives: ["مش شغّال", "معطّل"] },
      { id: "arv269", english: "To book online", arabic: "حجز عبر الإنترنت", target: "حجز عبر الإنترنت", transliteration: "ḥajaza ʿabra l-internet", alternatives: ["يحجز أونلاين"] },
      { id: "arv270", english: "A video call", arabic: "مكالمة مرئية", target: "مكالمة مرئية", transliteration: "mukālama marʾiyya", alternatives: ["فيديو كول"] },
      { id: "arv271", english: "A notification", arabic: "إشعار", target: "إشعار", transliteration: "ishʿār", alternatives: ["نوتيفكيشن"] },
    ],
  },
];

export const arabicPhraseLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-p-a1-1",
    title: "A1 · Introducing yourself",
    cefr: "A1",
    cards: [
      { id: "arp001", english: "My name is Dave", arabic: "اسمي دايف", target: "اسمي دايف", transliteration: "ismī dāyf", alternatives: ["أنا اسمي دايف"] },
      { id: "arp002", english: "What is your name?", arabic: "ما اسمك؟", target: "ما اسمك", transliteration: "mā ismuk", alternatives: ["إيه اسمك", "شو اسمك"] },
      { id: "arp003", english: "Nice to meet you", arabic: "تشرّفت بمعرفتك", target: "تشرّفت بمعرفتك", transliteration: "tasharraftu bi-maʿrifatik", alternatives: ["فرصة سعيدة", "يسعدني لقاءك"] },
      { id: "arp004", english: "I am from Uganda", arabic: "أنا من أوغندا", target: "أنا من أوغندا", transliteration: "anā min ūghanda" },
      { id: "arp005", english: "Where are you from?", arabic: "من أين أنت؟", target: "من أين أنت", transliteration: "min ayna ant", alternatives: ["من وين أنت", "إنت منين"] },
      { id: "arp006", english: "I live in Cairo", arabic: "أنا أسكن في القاهرة", target: "أنا أسكن في القاهرة", transliteration: "anā askunu fī l-qāhira", alternatives: ["أنا ساكن في القاهرة"] },
      { id: "arp007", english: "I am 30 years old", arabic: "عمري ثلاثون سنة", target: "عمري ثلاثون سنة", transliteration: "ʿumrī thalāthūn sana", alternatives: ["عندي ثلاثين سنة"] },
      { id: "arp008", english: "I am a designer", arabic: "أنا مصمّم", target: "أنا مصمّم", transliteration: "anā muṣammim", alternatives: ["أنا ديزاينر"] },
      { id: "arp009", english: "I am married", arabic: "أنا متزوج", target: "أنا متزوج", transliteration: "anā mutazawwij", alternatives: ["أنا متزوجة"] },
      { id: "arp010", english: "I am single", arabic: "أنا أعزب", target: "أنا أعزب", transliteration: "anā aʿzab", alternatives: ["أنا عزباء", "أنا مش متجوّز"] },
      { id: "arp011", english: "I am learning Arabic", arabic: "أنا أتعلّم العربية", target: "أنا أتعلّم العربية", transliteration: "anā ataʿallamu l-ʿarabiyya", alternatives: ["بتعلّم عربي"] },
      { id: "arp012", english: "I speak a little Arabic", arabic: "أتكلّم قليلاً من العربية", target: "أتكلّم قليلاً من العربية", transliteration: "atakallamu qalīlan min al-ʿarabiyya", alternatives: ["بحكي شوية عربي"] },
    ],
  },

  {
    id: "ar-p-a1-2",
    title: "A1 · Survival & asking for help",
    cefr: "A1",
    cards: [
      { id: "arp013", english: "I don't understand", arabic: "لا أفهم", target: "لا أفهم", transliteration: "lā afham", alternatives: ["ما فهمتش", "مش فاهم"] },
      { id: "arp014", english: "Can you repeat that?", arabic: "هل يمكنك التكرار؟", target: "هل يمكنك التكرار", transliteration: "hal yumkinuka t-tikrār", alternatives: ["ممكن تعيد", "تقدر تكرر"] },
      { id: "arp015", english: "Speak more slowly please", arabic: "تكلّم ببطء من فضلك", target: "تكلّم ببطء من فضلك", transliteration: "takallam bi-buṭʾ min faḍlak", alternatives: ["ابطأ شوية لو سمحت"] },
      { id: "arp016", english: "Do you speak English?", arabic: "هل تتكلّم الإنجليزية؟", target: "هل تتكلّم الإنجليزية", transliteration: "hal tatakallamu l-inglīziyya", alternatives: ["بتحكي إنجليزي"] },
      { id: "arp017", english: "Where is the bathroom?", arabic: "أين الحمام؟", target: "أين الحمام", transliteration: "ayna l-ḥammām", alternatives: ["فين الحمام", "وين التواليت"] },
      { id: "arp018", english: "How much does this cost?", arabic: "كم ثمن هذا؟", target: "كم ثمن هذا", transliteration: "kam thamanu hādhā", alternatives: ["بكم ده", "كم سعره"] },
      { id: "arp019", english: "I would like...", arabic: "أريد...", target: "أريد", transliteration: "urīdu", alternatives: ["أنا عايز", "بدّي"] },
      { id: "arp020", english: "Do you have...?", arabic: "هل عندك...؟", target: "هل عندك", transliteration: "hal ʿindak", alternatives: ["عندك", "فيه عندك"] },
      { id: "arp021", english: "Help!", arabic: "النجدة!", target: "النجدة", transliteration: "an-najda", alternatives: ["ساعدني", "مساعدة"] },
      { id: "arp022", english: "I am lost", arabic: "أنا ضائع", target: "أنا ضائع", transliteration: "anā ḍāʾiʿ", alternatives: ["أنا تهت", "مش عارف أرجع"] },
      { id: "arp023", english: "I don't know", arabic: "لا أعرف", target: "لا أعرف", transliteration: "lā aʿrif", alternatives: ["ما أعرفش", "مش عارف"] },
      { id: "arp024", english: "What does this mean?", arabic: "ماذا يعني هذا؟", target: "ماذا يعني هذا", transliteration: "mādhā yaʿnī hādhā", alternatives: ["يعني إيه ده", "شو يعني هيك"] },
    ],
  },

  {
    id: "ar-p-a1-3",
    title: "A1 · At the restaurant & café",
    cefr: "A1",
    cards: [
      { id: "arp025", english: "A table for two please", arabic: "طاولة لشخصين من فضلك", target: "طاولة لشخصين من فضلك", transliteration: "ṭāwila li-shakhṣayn min faḍlak", alternatives: ["ترابيزة لاتنين لو سمحت"] },
      { id: "arp026", english: "The menu please", arabic: "القائمة من فضلك", target: "القائمة من فضلك", transliteration: "al-qāʾima min faḍlak", alternatives: ["المنيو لو سمحت"] },
      { id: "arp027", english: "I would like a coffee", arabic: "أريد قهوة", target: "أريد قهوة", transliteration: "urīdu qahwa", alternatives: ["عايز قهوة", "بدّي قهوة"] },
      { id: "arp028", english: "A glass of water please", arabic: "كوب ماء من فضلك", target: "كوب ماء من فضلك", transliteration: "kūb māʾ min faḍlak" },
      { id: "arp029", english: "The bill please", arabic: "الحساب من فضلك", target: "الحساب من فضلك", transliteration: "al-ḥisāb min faḍlak", alternatives: ["الحساب لو سمحت"] },
      { id: "arp030", english: "It is delicious", arabic: "إنه لذيذ", target: "إنه لذيذ", transliteration: "innahu ladhīdh", alternatives: ["طيّب كتير", "زاكي"] },
      { id: "arp031", english: "I am vegetarian", arabic: "أنا نباتي", target: "أنا نباتي", transliteration: "anā nabātī", alternatives: ["أنا نباتية"] },
      { id: "arp032", english: "Without meat please", arabic: "بدون لحم من فضلك", target: "بدون لحم من فضلك", transliteration: "bi-dūni laḥm min faḍlak", alternatives: ["من غير لحمة"] },
      { id: "arp033", english: "Is service included?", arabic: "هل الخدمة مشمولة؟", target: "هل الخدمة مشمولة", transliteration: "hal al-khidma mashmūla", alternatives: ["الخدمة مدفوعة"] },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-p-a2-1",
    title: "A2 · Making plans & social life",
    cefr: "A2",
    cards: [
      { id: "arp034", english: "Are you free this evening?", arabic: "هل أنت حر هذا المساء؟", target: "هل أنت حر هذا المساء", transliteration: "hal anta ḥurr hādhā l-masāʾ", alternatives: ["إنت فاضي الليلة", "فاضي الليلة"] },
      { id: "arp035", english: "Do you want to come?", arabic: "هل تريد أن تأتي؟", target: "هل تريد أن تأتي", transliteration: "hal turīdu an taʾtī", alternatives: ["تعال معنا", "عايز تيجي"] },
      { id: "arp036", english: "I'd love to", arabic: "بكل سرور", target: "بكل سرور", transliteration: "bi-kulli surūr", alternatives: ["حبّاً وكرامة", "يلا تمام"] },
      { id: "arp037", english: "Sorry I can't", arabic: "آسف لا أستطيع", target: "آسف لا أستطيع", transliteration: "āsif lā astaṭīʿ", alternatives: ["معلش ما قدرش", "أنا آسف مش قادر"] },
      { id: "arp038", english: "Maybe another time", arabic: "ربما في وقت آخر", target: "ربما في وقت آخر", transliteration: "rubbamā fī waqt ākhar", alternatives: ["إن شاء الله مرة ثانية"] },
      { id: "arp039", english: "Let's meet at...", arabic: "لنلتقي في...", target: "لنلتقي في", transliteration: "li-naltaqī fī", alternatives: ["يلا نتقابل في", "نتلاقى في"] },
      { id: "arp040", english: "I'll be there at 8", arabic: "سأكون هناك الساعة الثامنة", target: "سأكون هناك الساعة الثامنة", transliteration: "sa-akūnu hunāka s-sāʿa th-thāmina", alternatives: ["هكون هناك الساعة تمانية"] },
      { id: "arp041", english: "I'm running late", arabic: "أنا متأخر", target: "أنا متأخر", transliteration: "anā mutaʾakhkhir", alternatives: ["أنا تأخرت", "أنا متأخّر شوية"] },
      { id: "arp042", english: "I had a great time", arabic: "استمتعت جداً", target: "استمتعت جداً", transliteration: "istamtaʿtu jiddan", alternatives: ["كانت وقتاً رائعاً", "بسطت كتير"] },
      { id: "arp043", english: "What do you want to do?", arabic: "ماذا تريد أن تفعل؟", target: "ماذا تريد أن تفعل", transliteration: "mādhā turīdu an tafʿal", alternatives: ["إيه اللي إنت عايزه", "شو بدّك تعمل"] },
      { id: "arp044", english: "I prefer...", arabic: "أفضّل...", target: "أفضّل", transliteration: "ufaḍḍilu", alternatives: ["أنا أحبّ أكثر"] },
    ],
  },

  {
    id: "ar-p-a2-2",
    title: "A2 · Talking about the past",
    cefr: "A2",
    cards: [
      { id: "arp045", english: "I went to...", arabic: "ذهبت إلى...", target: "ذهبت إلى", transliteration: "dhahabtu ilā", alternatives: ["رحت لـ", "مشيت لـ"] },
      { id: "arp046", english: "I ate...", arabic: "أكلت...", target: "أكلت", transliteration: "akaltu" },
      { id: "arp047", english: "I saw", arabic: "رأيت", target: "رأيت", transliteration: "raʾaytu", alternatives: ["شفت"] },
      { id: "arp048", english: "I did / I made", arabic: "فعلت", target: "فعلت", transliteration: "faʿaltu", alternatives: ["عملت"] },
      { id: "arp049", english: "I bought", arabic: "اشتريت", target: "اشتريت", transliteration: "ishtaraytu" },
      { id: "arp050", english: "Yesterday I...", arabic: "أمس...", target: "أمس", transliteration: "ams", alternatives: ["امبارح"] },
      { id: "arp051", english: "Last week", arabic: "الأسبوع الماضي", target: "الأسبوع الماضي", transliteration: "al-usbūʿ al-māḍī", alternatives: ["الأسبوع اللي فات"] },
      { id: "arp052", english: "It was...", arabic: "كان...", target: "كان", transliteration: "kāna" },
      { id: "arp053", english: "There was / there were", arabic: "كان هناك", target: "كان هناك", transliteration: "kāna hunāka", alternatives: ["كان في", "فيه"] },
      { id: "arp054", english: "I didn't...", arabic: "لم أفعل...", target: "لم أفعل", transliteration: "lam afʿal", alternatives: ["ما عملتش", "ما فعلتش"] },
      { id: "arp055", english: "Did you...?", arabic: "هل فعلت...؟", target: "هل فعلت", transliteration: "hal faʿalta", alternatives: ["إنت عملت", "عملت"] },
      { id: "arp056", english: "It was great", arabic: "كان رائعاً", target: "كان رائعاً", transliteration: "kāna rāʾiʿan", alternatives: ["كان تمام", "كان حلو"] },
    ],
  },

  {
    id: "ar-p-a2-3",
    title: "A2 · Describing your day",
    cefr: "A2",
    cards: [
      { id: "arp057", english: "I wake up at 7", arabic: "أستيقظ الساعة السابعة", target: "أستيقظ الساعة السابعة", transliteration: "astayqiẓu s-sāʿata s-sābiʿa", alternatives: ["بصحى الساعة سبعة"] },
      { id: "arp058", english: "I take the metro to work", arabic: "أخذ المترو للعمل", target: "أخذ المترو للعمل", transliteration: "ākhudhu l-mitrū lil-ʿamal", alternatives: ["بروح الشغل بالمترو"] },
      { id: "arp059", english: "I work from home", arabic: "أعمل من المنزل", target: "أعمل من المنزل", transliteration: "aʿmalu min al-manzil", alternatives: ["بشتغل من البيت"] },
      { id: "arp060", english: "I finish work at 6", arabic: "أنهي العمل الساعة السادسة", target: "أنهي العمل الساعة السادسة", transliteration: "anhī l-ʿamala s-sāʿata s-sādisa", alternatives: ["بخلّص شغل الساعة ستة"] },
      { id: "arp061", english: "In the evening I cook", arabic: "في المساء أطبخ", target: "في المساء أطبخ", transliteration: "fī l-masāʾi aṭbukhu", alternatives: ["بالليل بطبخ"] },
      { id: "arp062", english: "I usually...", arabic: "عادةً...", target: "عادةً", transliteration: "ʿādatan", alternatives: ["في الغالب", "دايماً تقريباً"] },
      { id: "arp063", english: "Sometimes I...", arabic: "أحياناً...", target: "أحياناً", transliteration: "aḥyānan", alternatives: ["بعض الأحيان"] },
      { id: "arp064", english: "Every day I...", arabic: "كل يوم...", target: "كل يوم", transliteration: "kulla yawm" },
      { id: "arp065", english: "On weekends I...", arabic: "في عطلة نهاية الأسبوع...", target: "في عطلة نهاية الأسبوع", transliteration: "fī ʿuṭlat nihāyat al-usbūʿ", alternatives: ["في الويكند"] },
      { id: "arp066", english: "I never...", arabic: "لا أفعل أبداً", target: "لا أفعل أبداً", transliteration: "lā afʿalu abadan", alternatives: ["ما بعملش أبداً"] },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────

  {
    id: "ar-p-b1-1",
    title: "B1 · Giving opinions & debating",
    cefr: "B1",
    cards: [
      { id: "arp067", english: "I agree", arabic: "أنا موافق", target: "أنا موافق", transliteration: "anā muwāfiq", alternatives: ["أنا متّفق معك", "صح"] },
      { id: "arp068", english: "I don't agree", arabic: "أنا لا أوافق", target: "أنا لا أوافق", transliteration: "anā lā uwāfiq", alternatives: ["مش موافق", "مش متّفق"] },
      { id: "arp069", english: "You're right", arabic: "أنت محقّ", target: "أنت محقّ", transliteration: "anta muḥiqq", alternatives: ["أنت صح", "معك حق"] },
      { id: "arp070", english: "You're wrong", arabic: "أنت مخطئ", target: "أنت مخطئ", transliteration: "anta mukhṭiʾ", alternatives: ["أنت غلطان", "ده مش صح"] },
      { id: "arp071", english: "I find that...", arabic: "أجد أنّ...", target: "أجد أنّ", transliteration: "ajidu anna", alternatives: ["أنا لاقي إن", "بلاقي إن"] },
      { id: "arp072", english: "It seems to me that...", arabic: "يبدو لي أنّ...", target: "يبدو لي أنّ", transliteration: "yabdū lī anna", alternatives: ["من وجهة نظري", "بحسّ إن"] },
      { id: "arp073", english: "I'm not sure", arabic: "لست متأكّداً", target: "لست متأكّداً", transliteration: "lastu mutaʾakkidan", alternatives: ["مش متأكّد", "مش عارف بالضبط"] },
      { id: "arp074", english: "That depends", arabic: "يعتمد على الموقف", target: "يعتمد على الموقف", transliteration: "yaʿtamidu ʿalā l-mawqif", alternatives: ["على حسب", "حسب الأحوال"] },
      { id: "arp075", english: "That's a good point", arabic: "هذه نقطة جيّدة", target: "هذه نقطة جيّدة", transliteration: "hādhihi nuqṭa jayyida", alternatives: ["ده كلام صح", "نقطة كويّسة"] },
      { id: "arp076", english: "What do you think?", arabic: "ما رأيك؟", target: "ما رأيك", transliteration: "mā raʾyuk", alternatives: ["إيه رأيك", "شو رأيك"] },
      { id: "arp077", english: "Personally I think...", arabic: "شخصياً أعتقد أنّ...", target: "شخصياً أعتقد أنّ", transliteration: "shakhṣiyyan aʿtaqidu anna", alternatives: ["أنا شخصياً شايف"] },
      { id: "arp078", english: "Let me explain", arabic: "دعني أشرح", target: "دعني أشرح", transliteration: "daʿnī ashraḥ", alternatives: ["خلّيني أوضّح", "بشرح لك"] },
      { id: "arp079", english: "I hadn't thought of that", arabic: "لم أفكّر في ذلك", target: "لم أفكّر في ذلك", transliteration: "lam ufakkir fī dhālik", alternatives: ["ما فكّرتش في كده"] },
    ],
  },

  {
    id: "ar-p-b1-2",
    title: "B1 · Talking about the future",
    cefr: "B1",
    cards: [
      { id: "arp080", english: "I'm going to...", arabic: "سأقوم بـ...", target: "سأقوم بـ", transliteration: "sa-aqūmu bi-", alternatives: ["رح أعمل", "هعمل"] },
      { id: "arp081", english: "I plan to...", arabic: "أخطّط لـ...", target: "أخطّط لـ", transliteration: "ukhaṭṭiṭu li-", alternatives: ["ناوي أعمل", "قررت"] },
      { id: "arp082", english: "I hope to...", arabic: "أتمنّى أن...", target: "أتمنّى أن", transliteration: "atamannā an", alternatives: ["بتمنّى", "يا ريت"] },
      { id: "arp083", english: "I would like to...", arabic: "أودّ أن...", target: "أودّ أن", transliteration: "awaddu an", alternatives: ["أنا نفسي أعمل", "عايز"] },
      { id: "arp084", english: "God willing it will happen", arabic: "إن شاء الله هيحصل", target: "إن شاء الله هيحصل", transliteration: "in shāʾa llāh hayiḥṣal" },
      { id: "arp085", english: "One day I want to...", arabic: "يوماً ما أريد أن...", target: "يوماً ما أريد أن", transliteration: "yawman mā urīdu an", alternatives: ["يوم من الأيام بدّي"] },
      { id: "arp086", english: "Next year", arabic: "السنة القادمة", target: "السنة القادمة", transliteration: "as-sana l-qādima", alternatives: ["العام الجاي"] },
      { id: "arp087", english: "In the future", arabic: "في المستقبل", target: "في المستقبل", transliteration: "fī l-mustaqbal" },
      { id: "arp088", english: "My dream is to...", arabic: "حلمي هو أن...", target: "حلمي هو أن", transliteration: "ḥulmī huwa an", alternatives: ["أنا بحلم إنّي"] },
      { id: "arp089", english: "We'll see", arabic: "سنرى", target: "سنرى", transliteration: "sa-narā", alternatives: ["نشوف", "الأيام بتقول"] },
      { id: "arp090", english: "It's possible that...", arabic: "من المحتمل أن...", target: "من المحتمل أن", transliteration: "min al-muḥtamal an", alternatives: ["يمكن", "ممكن"] },
    ],
  },

  {
    id: "ar-p-b1-3",
    title: "B1 · Complaints & polite requests",
    cefr: "B1",
    cards: [
      { id: "arp091", english: "There's a problem with...", arabic: "هناك مشكلة في...", target: "هناك مشكلة في", transliteration: "hunāka mushkila fī", alternatives: ["فيه مشكلة في", "في مشكلة"] },
      { id: "arp092", english: "This doesn't work", arabic: "هذا لا يعمل", target: "هذا لا يعمل", transliteration: "hādhā lā yaʿmal", alternatives: ["ده مش شغّال", "مش بيشتغل"] },
      { id: "arp093", english: "Could you please...?", arabic: "هل يمكنك...؟", target: "هل يمكنك", transliteration: "hal yumkinuka", alternatives: ["ممكن تعمل", "تقدر"] },
      { id: "arp094", english: "I'm not satisfied", arabic: "أنا لست راضياً", target: "أنا لست راضياً", transliteration: "anā lastu rāḍiyan", alternatives: ["أنا مش راضي", "مش مبسوط"] },
      { id: "arp095", english: "Can I speak to the manager?", arabic: "هل يمكنني التحدّث مع المدير؟", target: "هل يمكنني التحدّث مع المدير", transliteration: "hal yumkinunī t-taḥadduthu maʿa l-mudīr", alternatives: ["عايز أكلّم المسؤول"] },
      { id: "arp096", english: "I'd like a refund", arabic: "أريد استرداد المبلغ", target: "أريد استرداد المبلغ", transliteration: "urīdu stirdāda l-mablagh", alternatives: ["عايز أسترجع فلوسي"] },
      { id: "arp097", english: "It's not what I expected", arabic: "هذا ليس ما توقّعته", target: "هذا ليس ما توقّعته", transliteration: "hādhā laysa mā tawaqaʿtuhu", alternatives: ["ده مش اللي توقّعته"] },
      { id: "arp098", english: "I've been waiting for...", arabic: "أنا أنتظر منذ...", target: "أنا أنتظر منذ", transliteration: "anā antaẓiru mundhu", alternatives: ["أنا مستنّي من"] },
      { id: "arp099", english: "Thank you for your help", arabic: "شكراً على مساعدتك", target: "شكراً على مساعدتك", transliteration: "shukran ʿalā musāʿadatik", alternatives: ["مشكور على المساعدة"] },
    ],
  },

  {
    id: "ar-p-b1-4",
    title: "B1 · Storytelling & narrating",
    cefr: "B1",
    cards: [
      { id: "arp100", english: "So what happened was...", arabic: "إذن ما حدث هو...", target: "إذن ما حدث هو", transliteration: "idhan mā ḥadatha huwa", alternatives: ["اللي حصل إن", "يعني اللي صار"] },
      { id: "arp101", english: "At first...", arabic: "في البداية...", target: "في البداية", transliteration: "fī l-bidāya", alternatives: ["أوّلاً", "من البداية"] },
      { id: "arp102", english: "Then...", arabic: "ثم...", target: "ثم", transliteration: "thumma", alternatives: ["وبعدين", "وبعد كده"] },
      { id: "arp103", english: "Finally...", arabic: "في النهاية...", target: "في النهاية", transliteration: "fī n-nihāya", alternatives: ["وآخر شيء"] },
      { id: "arp104", english: "Suddenly...", arabic: "فجأةً...", target: "فجأةً", transliteration: "fajʾatan", alternatives: ["على غفلة", "وفجأة"] },
      { id: "arp105", english: "In the end...", arabic: "في الأخير...", target: "في الأخير", transliteration: "fī l-akhīr", alternatives: ["آخر الكلام", "بالنهاية"] },
      { id: "arp106", english: "The thing is...", arabic: "المشكلة هي أنّ...", target: "المشكلة هي أنّ", transliteration: "al-mushkila hiya anna", alternatives: ["يعني المسألة إن", "الموضوع إنّو"] },
      { id: "arp107", english: "Can you believe it?", arabic: "هل تصدّق؟", target: "هل تصدّق", transliteration: "hal tuṣaddiq", alternatives: ["تصوّر", "عارف إيه صار"] },
      { id: "arp108", english: "Long story short", arabic: "باختصار", target: "باختصار", transliteration: "bikhtisār", alternatives: ["المهم", "يعني بكل قصر"] },
      { id: "arp109", english: "I swear / honestly", arabic: "والله", target: "والله", transliteration: "wallāh", alternatives: ["والله العظيم", "صدقاً"] },
    ],
  },

  {
    id: "ar-p-b1-5",
    title: "B1 · Expressing feelings in conversation",
    cefr: "B1",
    cards: [
      { id: "arp110", english: "I'm really happy for you", arabic: "أنا سعيد جداً لأجلك", target: "أنا سعيد جداً لأجلك", transliteration: "anā saʿīd jiddan li-ajlik", alternatives: ["مبسوط عشانك", "يا هنيّالك"] },
      { id: "arp111", english: "I'm sorry to hear that", arabic: "أنا آسف لسماع ذلك", target: "أنا آسف لسماع ذلك", transliteration: "anā āsif li-samāʿi dhālik", alternatives: ["يا خسارة", "حرام عليك"] },
      { id: "arp112", english: "What a shame / pity", arabic: "يا للأسف", target: "يا للأسف", transliteration: "yā lil-asaf", alternatives: ["يا حرام", "يا خسارة"] },
      { id: "arp113", english: "That's wonderful!", arabic: "هذا رائع!", target: "هذا رائع", transliteration: "hādhā rāʾiʿ", alternatives: ["ممتاز", "يا جمال", "روعة"] },
      { id: "arp114", english: "I miss you", arabic: "أنا مشتاق لك", target: "أنا مشتاق لك", transliteration: "anā mushtāq lak", alternatives: ["اشتقتلك", "وحشتني"] },
      { id: "arp115", english: "Take care of yourself", arabic: "اعتنِ بنفسك", target: "اعتنِ بنفسك", transliteration: "iʿtanī bi-nafsik", alternatives: ["خلّي بالك من نفسك", "على بالك"] },
      { id: "arp116", english: "Don't worry", arabic: "لا تقلق", target: "لا تقلق", transliteration: "lā taqlaق", alternatives: ["ما تخافش", "ما في مشكلة"] },
      { id: "arp117", english: "Congratulations!", arabic: "مبروك!", target: "مبروك", transliteration: "mabrūk", alternatives: ["تهانيّ", "ألف مبروك"] },
      { id: "arp118", english: "Get well soon", arabic: "سلامتك", target: "سلامتك", transliteration: "salāmatak", alternatives: ["الله يشفيك"] },
      { id: "arp119", english: "Good luck!", arabic: "بالتوفيق!", target: "بالتوفيق", transliteration: "bit-tawfīq", alternatives: ["حظاً موفقاً", "ربنا يوفّقك"] },
    ],
  },
];
