export interface FlashcardItem {
  id: string;
  english: string;
  french?: string;
  arabic?: string;
  target: string;
  alternatives?: string[];
  dialect?: string;
}

export interface Level {
  id: string;
  title: string;
  cefr?: "A1" | "A2" | "B1";
  cards: FlashcardItem[];
}

// ─────────────────────────────────────────────────────────────────────────────
// FRENCH — VOCABULARY LEVELS
// ─────────────────────────────────────────────────────────────────────────────

export const vocabularyLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-a1-1",
    title: "A1 · Greetings & basics",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-1-c01", english: "Hello / Good day",       target: "Bonjour" },
      { id: "fr-v-a1-1-c02", english: "Good evening",           target: "Bonsoir" },
      { id: "fr-v-a1-1-c03", english: "Hi / Bye (informal)",    target: "Salut" },
      { id: "fr-v-a1-1-c04", english: "Goodbye",                target: "Au revoir" },
      { id: "fr-v-a1-1-c05", english: "See you soon",           target: "À bientôt" },
      { id: "fr-v-a1-1-c06", english: "See you tomorrow",       target: "À demain" },
      { id: "fr-v-a1-1-c07", english: "Please",                 target: "S'il vous plaît", alternatives: ["S'il te plaît"] },
      { id: "fr-v-a1-1-c08", english: "Thank you",              target: "Merci" },
      { id: "fr-v-a1-1-c09", english: "Thank you very much",    target: "Merci beaucoup" },
      { id: "fr-v-a1-1-c10", english: "You're welcome",         target: "De rien" },
      { id: "fr-v-a1-1-c11", english: "Sorry / Excuse me",      target: "Pardon" },
      { id: "fr-v-a1-1-c12", english: "Excuse me (formal)",     target: "Excusez-moi" },
      { id: "fr-v-a1-1-c13", english: "Yes",                    target: "Oui" },
      { id: "fr-v-a1-1-c14", english: "No",                     target: "Non" },
      { id: "fr-v-a1-1-c15", english: "OK / alright",           target: "D'accord" },
    ],
  },

  {
    id: "fr-v-a1-2",
    title: "A1 · Numbers & time",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-2-c01", english: "One",                    target: "Un" },
      { id: "fr-v-a1-2-c02", english: "Two",                    target: "Deux" },
      { id: "fr-v-a1-2-c03", english: "Three",                  target: "Trois" },
      { id: "fr-v-a1-2-c04", english: "Four",                   target: "Quatre" },
      { id: "fr-v-a1-2-c05", english: "Five",                   target: "Cinq" },
      { id: "fr-v-a1-2-c06", english: "Ten",                    target: "Dix" },
      { id: "fr-v-a1-2-c07", english: "Twenty",                 target: "Vingt" },
      { id: "fr-v-a1-2-c08", english: "Thirty",                 target: "Trente" },
      { id: "fr-v-a1-2-c09", english: "One hundred",            target: "Cent" },
      { id: "fr-v-a1-2-c10", english: "One thousand",           target: "Mille" },
      { id: "fr-v-a1-2-c11", english: "What time is it?",       target: "Quelle heure est-il" },
      { id: "fr-v-a1-2-c12", english: "It is 3 o'clock",        target: "Il est trois heures" },
      { id: "fr-v-a1-2-c13", english: "In the morning",         target: "Du matin" },
      { id: "fr-v-a1-2-c14", english: "In the afternoon",       target: "De l'après-midi" },
      { id: "fr-v-a1-2-c15", english: "At noon",                target: "À midi" },
      { id: "fr-v-a1-2-c16", english: "At midnight",            target: "À minuit" },
      { id: "fr-v-a1-2-c17", english: "Half past",              target: "Et demie" },
      { id: "fr-v-a1-2-c18", english: "Quarter past",           target: "Et quart" },
    ],
  },

  {
    id: "fr-v-a1-3",
    title: "A1 · Days & months",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-3-c01", english: "Monday",                 target: "Lundi" },
      { id: "fr-v-a1-3-c02", english: "Tuesday",                target: "Mardi" },
      { id: "fr-v-a1-3-c03", english: "Wednesday",              target: "Mercredi" },
      { id: "fr-v-a1-3-c04", english: "Thursday",               target: "Jeudi" },
      { id: "fr-v-a1-3-c05", english: "Friday",                 target: "Vendredi" },
      { id: "fr-v-a1-3-c06", english: "Saturday",               target: "Samedi" },
      { id: "fr-v-a1-3-c07", english: "Sunday",                 target: "Dimanche" },
      { id: "fr-v-a1-3-c08", english: "Today",                  target: "Aujourd'hui" },
      { id: "fr-v-a1-3-c09", english: "Tomorrow",               target: "Demain" },
      { id: "fr-v-a1-3-c10", english: "Yesterday",              target: "Hier" },
      { id: "fr-v-a1-3-c11", english: "This week",              target: "Cette semaine" },
      { id: "fr-v-a1-3-c12", english: "Next week",              target: "La semaine prochaine" },
      { id: "fr-v-a1-3-c13", english: "January",                target: "Janvier" },
      { id: "fr-v-a1-3-c14", english: "February",               target: "Février" },
      { id: "fr-v-a1-3-c15", english: "March",                  target: "Mars" },
      { id: "fr-v-a1-3-c16", english: "June",                   target: "Juin" },
      { id: "fr-v-a1-3-c17", english: "December",               target: "Décembre" },
      { id: "fr-v-a1-3-c18", english: "Now",                    target: "Maintenant" },
      { id: "fr-v-a1-3-c19", english: "Soon",                   target: "Bientôt" },
      { id: "fr-v-a1-3-c20", english: "Always / never",         target: "Toujours", alternatives: ["Jamais"] },
    ],
  },

  {
    id: "fr-v-a1-4",
    title: "A1 · Core verbs",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-4-c01", english: "To be",                  target: "Être" },
      { id: "fr-v-a1-4-c02", english: "To have",                target: "Avoir" },
      { id: "fr-v-a1-4-c03", english: "To go",                  target: "Aller" },
      { id: "fr-v-a1-4-c04", english: "To do / make",           target: "Faire" },
      { id: "fr-v-a1-4-c05", english: "To want",                target: "Vouloir" },
      { id: "fr-v-a1-4-c06", english: "To be able to",          target: "Pouvoir" },
      { id: "fr-v-a1-4-c07", english: "To know (a fact)",       target: "Savoir" },
      { id: "fr-v-a1-4-c08", english: "To know (a person)",     target: "Connaître" },
      { id: "fr-v-a1-4-c09", english: "To come",                target: "Venir" },
      { id: "fr-v-a1-4-c10", english: "To see",                 target: "Voir" },
      { id: "fr-v-a1-4-c11", english: "To speak",               target: "Parler" },
      { id: "fr-v-a1-4-c12", english: "To eat",                 target: "Manger" },
      { id: "fr-v-a1-4-c13", english: "To drink",               target: "Boire" },
      { id: "fr-v-a1-4-c14", english: "To live / stay",         target: "Habiter" },
      { id: "fr-v-a1-4-c15", english: "To need / must",         target: "Devoir" },
    ],
  },

  {
    id: "fr-v-a1-5",
    title: "A1 · People & family",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-5-c01", english: "Man",                    target: "Un homme" },
      { id: "fr-v-a1-5-c02", english: "Woman",                  target: "Une femme" },
      { id: "fr-v-a1-5-c03", english: "Child",                  target: "Un enfant" },
      { id: "fr-v-a1-5-c04", english: "Boy",                    target: "Un garçon" },
      { id: "fr-v-a1-5-c05", english: "Girl",                   target: "Une fille" },
      { id: "fr-v-a1-5-c06", english: "Friend",                 target: "Un ami", alternatives: ["Une amie"] },
      { id: "fr-v-a1-5-c07", english: "Father",                 target: "Le père" },
      { id: "fr-v-a1-5-c08", english: "Mother",                 target: "La mère" },
      { id: "fr-v-a1-5-c09", english: "Brother",                target: "Le frère" },
      { id: "fr-v-a1-5-c10", english: "Sister",                 target: "La sœur" },
      { id: "fr-v-a1-5-c11", english: "Parents",                target: "Les parents" },
      { id: "fr-v-a1-5-c12", english: "Family",                 target: "La famille" },
      { id: "fr-v-a1-5-c13", english: "Grandfather",            target: "Le grand-père" },
      { id: "fr-v-a1-5-c14", english: "My name is",             target: "Je m'appelle" },
      { id: "fr-v-a1-5-c15", english: "I am ... years old",     target: "J'ai ... ans" },
    ],
  },

  {
    id: "fr-v-a1-6",
    title: "A1 · Food & drink",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-6-c01", english: "Water",                  target: "De l'eau" },
      { id: "fr-v-a1-6-c02", english: "Coffee",                 target: "Un café" },
      { id: "fr-v-a1-6-c03", english: "Tea",                    target: "Un thé" },
      { id: "fr-v-a1-6-c04", english: "Wine",                   target: "Du vin" },
      { id: "fr-v-a1-6-c05", english: "Beer",                   target: "Une bière" },
      { id: "fr-v-a1-6-c06", english: "Bread",                  target: "Du pain" },
      { id: "fr-v-a1-6-c07", english: "Cheese",                 target: "Du fromage" },
      { id: "fr-v-a1-6-c08", english: "Meat",                   target: "De la viande" },
      { id: "fr-v-a1-6-c09", english: "Fish",                   target: "Du poisson" },
      { id: "fr-v-a1-6-c10", english: "Chicken",                target: "Du poulet" },
      { id: "fr-v-a1-6-c11", english: "Salad",                  target: "Une salade" },
      { id: "fr-v-a1-6-c12", english: "Dessert",                target: "Un dessert" },
      { id: "fr-v-a1-6-c13", english: "The bill",               target: "L'addition" },
      { id: "fr-v-a1-6-c14", english: "A table for two",        target: "Une table pour deux" },
      { id: "fr-v-a1-6-c15", english: "I am hungry",            target: "J'ai faim" },
      { id: "fr-v-a1-6-c16", english: "I am thirsty",           target: "J'ai soif" },
      { id: "fr-v-a1-6-c17", english: "Delicious",              target: "Délicieux" },
      { id: "fr-v-a1-6-c18", english: "Juice",                  target: "Un jus" },
    ],
  },

  {
    id: "fr-v-a1-7",
    title: "A1 · Places & directions",
    cefr: "A1",
    cards: [
      { id: "fr-v-a1-7-c01", english: "The city / town",        target: "La ville" },
      { id: "fr-v-a1-7-c02", english: "The street",             target: "La rue" },
      { id: "fr-v-a1-7-c03", english: "The train station",      target: "La gare" },
      { id: "fr-v-a1-7-c04", english: "The airport",            target: "L'aéroport" },
      { id: "fr-v-a1-7-c05", english: "The hospital",           target: "L'hôpital" },
      { id: "fr-v-a1-7-c06", english: "The pharmacy",           target: "La pharmacie" },
      { id: "fr-v-a1-7-c07", english: "The bank",               target: "La banque" },
      { id: "fr-v-a1-7-c08", english: "The supermarket",        target: "Le supermarché" },
      { id: "fr-v-a1-7-c09", english: "The hotel",              target: "L'hôtel" },
      { id: "fr-v-a1-7-c10", english: "On the left",            target: "À gauche" },
      { id: "fr-v-a1-7-c11", english: "On the right",           target: "À droite" },
      { id: "fr-v-a1-7-c12", english: "Straight ahead",         target: "Tout droit" },
      { id: "fr-v-a1-7-c13", english: "Near / close",           target: "Près" },
      { id: "fr-v-a1-7-c14", english: "Far",                    target: "Loin" },
      { id: "fr-v-a1-7-c15", english: "The toilet",             target: "Les toilettes" },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-a2-1",
    title: "A2 · Everyday adjectives",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-1-c01", english: "Good",                   target: "Bon" },
      { id: "fr-v-a2-1-c02", english: "Bad",                    target: "Mauvais" },
      { id: "fr-v-a2-1-c03", english: "Big / tall",             target: "Grand" },
      { id: "fr-v-a2-1-c04", english: "Small",                  target: "Petit" },
      { id: "fr-v-a2-1-c05", english: "New",                    target: "Nouveau" },
      { id: "fr-v-a2-1-c06", english: "Old",                    target: "Vieux" },
      { id: "fr-v-a2-1-c07", english: "Beautiful",              target: "Beau" },
      { id: "fr-v-a2-1-c08", english: "Happy",                  target: "Heureux" },
      { id: "fr-v-a2-1-c09", english: "Sad",                    target: "Triste" },
      { id: "fr-v-a2-1-c10", english: "Tired",                  target: "Fatigué" },
      { id: "fr-v-a2-1-c11", english: "Busy",                   target: "Occupé" },
      { id: "fr-v-a2-1-c12", english: "Easy",                   target: "Facile" },
      { id: "fr-v-a2-1-c13", english: "Difficult",              target: "Difficile" },
      { id: "fr-v-a2-1-c14", english: "Expensive",              target: "Cher" },
      { id: "fr-v-a2-1-c15", english: "Cheap",                  target: "Pas cher" },
      { id: "fr-v-a2-1-c16", english: "Hot",                    target: "Chaud" },
      { id: "fr-v-a2-1-c17", english: "Cold",                   target: "Froid" },
      { id: "fr-v-a2-1-c18", english: "Open",                   target: "Ouvert" },
      { id: "fr-v-a2-1-c19", english: "Closed",                 target: "Fermé" },
      { id: "fr-v-a2-1-c20", english: "Interesting",            target: "Intéressant" },
    ],
  },

  {
    id: "fr-v-a2-2",
    title: "A2 · Daily routine",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-2-c01", english: "To wake up",             target: "Se réveiller" },
      { id: "fr-v-a2-2-c02", english: "To get up",              target: "Se lever" },
      { id: "fr-v-a2-2-c03", english: "To shower",              target: "Se doucher" },
      { id: "fr-v-a2-2-c04", english: "To get dressed",         target: "S'habiller" },
      { id: "fr-v-a2-2-c05", english: "To have breakfast",      target: "Prendre le petit-déjeuner" },
      { id: "fr-v-a2-2-c06", english: "To work",                target: "Travailler" },
      { id: "fr-v-a2-2-c07", english: "To study",               target: "Étudier" },
      { id: "fr-v-a2-2-c08", english: "To come back home",      target: "Rentrer à la maison" },
      { id: "fr-v-a2-2-c09", english: "To cook",                target: "Cuisiner", alternatives: ["Faire la cuisine"] },
      { id: "fr-v-a2-2-c10", english: "To watch TV",            target: "Regarder la télé" },
      { id: "fr-v-a2-2-c11", english: "To read",                target: "Lire" },
      { id: "fr-v-a2-2-c12", english: "To go to bed",           target: "Se coucher" },
      { id: "fr-v-a2-2-c13", english: "To sleep",               target: "Dormir" },
      { id: "fr-v-a2-2-c14", english: "To call (phone)",        target: "Appeler", alternatives: ["Téléphoner"] },
      { id: "fr-v-a2-2-c15", english: "To take the bus",        target: "Prendre le bus" },
    ],
  },

  {
    id: "fr-v-a2-3",
    title: "A2 · Shopping & money",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-3-c01", english: "To buy",                 target: "Acheter" },
      { id: "fr-v-a2-3-c02", english: "To pay",                 target: "Payer" },
      { id: "fr-v-a2-3-c03", english: "To cost",                target: "Coûter" },
      { id: "fr-v-a2-3-c04", english: "The price",              target: "Le prix" },
      { id: "fr-v-a2-3-c05", english: "Cash",                   target: "En espèces", alternatives: ["En liquide"] },
      { id: "fr-v-a2-3-c06", english: "Card payment",           target: "Par carte" },
      { id: "fr-v-a2-3-c07", english: "A receipt",              target: "Un reçu", alternatives: ["Un ticket"] },
      { id: "fr-v-a2-3-c08", english: "On sale",                target: "En solde" },
      { id: "fr-v-a2-3-c09", english: "The size",               target: "La taille" },
      { id: "fr-v-a2-3-c10", english: "Too big",                target: "Trop grand" },
      { id: "fr-v-a2-3-c11", english: "Too small",              target: "Trop petit" },
      { id: "fr-v-a2-3-c12", english: "I'm just looking",       target: "Je regarde seulement" },
      { id: "fr-v-a2-3-c13", english: "I'll take it",           target: "Je le prends" },
      { id: "fr-v-a2-3-c14", english: "Can I return this?",     target: "Je peux le rendre" },
      { id: "fr-v-a2-3-c15", english: "The change",             target: "La monnaie" },
    ],
  },

  {
    id: "fr-v-a2-4",
    title: "A2 · Transport & travel",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-4-c01", english: "The train",              target: "Le train" },
      { id: "fr-v-a2-4-c02", english: "The bus",                target: "Le bus" },
      { id: "fr-v-a2-4-c03", english: "The metro",              target: "Le métro" },
      { id: "fr-v-a2-4-c04", english: "The taxi",               target: "Le taxi" },
      { id: "fr-v-a2-4-c05", english: "The car",                target: "La voiture" },
      { id: "fr-v-a2-4-c06", english: "The plane",              target: "L'avion" },
      { id: "fr-v-a2-4-c07", english: "A single ticket",        target: "Un aller simple" },
      { id: "fr-v-a2-4-c08", english: "A return ticket",        target: "Un aller-retour" },
      { id: "fr-v-a2-4-c09", english: "The platform",           target: "Le quai" },
      { id: "fr-v-a2-4-c10", english: "The departure",          target: "Le départ" },
      { id: "fr-v-a2-4-c11", english: "The arrival",            target: "L'arrivée" },
      { id: "fr-v-a2-4-c12", english: "On time",                target: "À l'heure" },
      { id: "fr-v-a2-4-c13", english: "Late",                   target: "En retard" },
      { id: "fr-v-a2-4-c14", english: "A passport",             target: "Un passeport" },
      { id: "fr-v-a2-4-c15", english: "The luggage",            target: "Les bagages" },
    ],
  },

  {
    id: "fr-v-a2-5",
    title: "A2 · Health & body",
    cefr: "A2",
    cards: [
      { id: "fr-v-a2-5-c01", english: "I have a headache",      target: "J'ai mal à la tête" },
      { id: "fr-v-a2-5-c02", english: "I have a stomach ache",  target: "J'ai mal au ventre" },
      { id: "fr-v-a2-5-c03", english: "I feel sick",            target: "Je me sens mal" },
      { id: "fr-v-a2-5-c04", english: "I have a fever",         target: "J'ai de la fièvre" },
      { id: "fr-v-a2-5-c05", english: "A cold",                 target: "Un rhume" },
      { id: "fr-v-a2-5-c06", english: "The doctor",             target: "Le médecin" },
      { id: "fr-v-a2-5-c07", english: "A medicine",             target: "Un médicament" },
      { id: "fr-v-a2-5-c08", english: "An appointment",         target: "Un rendez-vous" },
      { id: "fr-v-a2-5-c09", english: "The head",               target: "La tête" },
      { id: "fr-v-a2-5-c10", english: "The back",               target: "Le dos" },
      { id: "fr-v-a2-5-c11", english: "The arm",                target: "Le bras" },
      { id: "fr-v-a2-5-c12", english: "The leg",                target: "La jambe" },
      { id: "fr-v-a2-5-c13", english: "To rest",                target: "Se reposer" },
      { id: "fr-v-a2-5-c14", english: "Allergic to",            target: "Allergique à" },
      { id: "fr-v-a2-5-c15", english: "It hurts here",          target: "J'ai mal ici" },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-v-b1-1",
    title: "B1 · Conversation connectors",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-1-c01", english: "So / then",              target: "Alors" },
      { id: "fr-v-b1-1-c02", english: "Well / right",           target: "Bon", alternatives: ["Ben"] },
      { id: "fr-v-b1-1-c03", english: "There you go",           target: "Voilà" },
      { id: "fr-v-b1-1-c04", english: "So / therefore (spoken)",target: "Du coup" },
      { id: "fr-v-b1-1-c05", english: "Actually / in fact",     target: "En fait" },
      { id: "fr-v-b1-1-c06", english: "Besides / moreover",     target: "En plus" },
      { id: "fr-v-b1-1-c07", english: "However / but",          target: "Par contre", alternatives: ["Mais"] },
      { id: "fr-v-b1-1-c08", english: "For example",            target: "Par exemple" },
      { id: "fr-v-b1-1-c09", english: "That's why",             target: "C'est pour ça que" },
      { id: "fr-v-b1-1-c10", english: "I mean / that is",       target: "C'est-à-dire" },
      { id: "fr-v-b1-1-c11", english: "To be honest",           target: "Franchement", alternatives: ["Honnêtement"] },
      { id: "fr-v-b1-1-c12", english: "In my opinion",          target: "À mon avis" },
      { id: "fr-v-b1-1-c13", english: "I think that",           target: "Je pense que", alternatives: ["Je crois que"] },
      { id: "fr-v-b1-1-c14", english: "It depends",             target: "Ça dépend" },
      { id: "fr-v-b1-1-c15", english: "Not really",             target: "Pas vraiment" },
      { id: "fr-v-b1-1-c16", english: "Exactly",                target: "Exactement", alternatives: ["Justement"] },
      { id: "fr-v-b1-1-c17", english: "More or less",           target: "Plus ou moins" },
      { id: "fr-v-b1-1-c18", english: "In general",             target: "En général" },
      { id: "fr-v-b1-1-c19", english: "At the same time",       target: "En même temps" },
      { id: "fr-v-b1-1-c20", english: "On the other hand",      target: "D'un autre côté" },
    ],
  },

  {
    id: "fr-v-b1-2",
    title: "B1 · Work & professional",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-2-c01", english: "A job / position",       target: "Un poste", alternatives: ["Un emploi"] },
      { id: "fr-v-b1-2-c02", english: "A company",              target: "Une entreprise", alternatives: ["Une société"] },
      { id: "fr-v-b1-2-c03", english: "A meeting",              target: "Une réunion" },
      { id: "fr-v-b1-2-c04", english: "A client",               target: "Un client" },
      { id: "fr-v-b1-2-c05", english: "A colleague",            target: "Un collègue" },
      { id: "fr-v-b1-2-c06", english: "The boss",               target: "Le patron", alternatives: ["Le chef"] },
      { id: "fr-v-b1-2-c07", english: "To work from home",      target: "Travailler à distance", alternatives: ["En télétravail"] },
      { id: "fr-v-b1-2-c08", english: "A deadline",             target: "Une date limite", alternatives: ["Un délai"] },
      { id: "fr-v-b1-2-c09", english: "A project",              target: "Un projet" },
      { id: "fr-v-b1-2-c10", english: "A salary",               target: "Un salaire" },
      { id: "fr-v-b1-2-c11", english: "To apply for a job",     target: "Postuler à un emploi" },
      { id: "fr-v-b1-2-c12", english: "An interview",           target: "Un entretien" },
      { id: "fr-v-b1-2-c13", english: "To hire",                target: "Embaucher", alternatives: ["Recruter"] },
      { id: "fr-v-b1-2-c14", english: "To resign",              target: "Démissionner" },
      { id: "fr-v-b1-2-c15", english: "A contract",             target: "Un contrat" },
      { id: "fr-v-b1-2-c16", english: "Leave / holiday",        target: "Un congé", alternatives: ["Des vacances"] },
      { id: "fr-v-b1-2-c17", english: "Self-employed",          target: "Indépendant", alternatives: ["Freelance"] },
      { id: "fr-v-b1-2-c18", english: "To manage / lead",       target: "Gérer", alternatives: ["Diriger"] },
    ],
  },

  {
    id: "fr-v-b1-3",
    title: "B1 · Emotions & feelings",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-3-c01", english: "I feel...",              target: "Je me sens" },
      { id: "fr-v-b1-3-c02", english: "Stressed",               target: "Stressé", alternatives: ["Anxieux"] },
      { id: "fr-v-b1-3-c03", english: "Excited",                target: "Enthousiaste", alternatives: ["Excité"] },
      { id: "fr-v-b1-3-c04", english: "Disappointed",           target: "Déçu" },
      { id: "fr-v-b1-3-c05", english: "Surprised",              target: "Surpris" },
      { id: "fr-v-b1-3-c06", english: "Relieved",               target: "Soulagé" },
      { id: "fr-v-b1-3-c07", english: "Proud",                  target: "Fier" },
      { id: "fr-v-b1-3-c08", english: "Worried",                target: "Inquiet" },
      { id: "fr-v-b1-3-c09", english: "Bored",                  target: "Je m'ennuie", alternatives: ["Ennuyé"] },
      { id: "fr-v-b1-3-c10", english: "Angry",                  target: "En colère", alternatives: ["Fâché"] },
      { id: "fr-v-b1-3-c11", english: "Nervous",                target: "Nerveux" },
      { id: "fr-v-b1-3-c12", english: "Comfortable",            target: "À l'aise" },
      { id: "fr-v-b1-3-c13", english: "I miss you",             target: "Tu me manques" },
      { id: "fr-v-b1-3-c14", english: "To love (something)",    target: "Adorer", alternatives: ["J'adore"] },
      { id: "fr-v-b1-3-c15", english: "To hate",                target: "Détester", alternatives: ["J'ai horreur de"] },
    ],
  },

  {
    id: "fr-v-b1-4",
    title: "B1 · Technology",
    cefr: "B1",
    cards: [
      { id: "fr-v-b1-4-c01", english: "A smartphone",           target: "Un smartphone", alternatives: ["Un téléphone"] },
      { id: "fr-v-b1-4-c02", english: "The internet",           target: "Internet" },
      { id: "fr-v-b1-4-c03", english: "Wi-Fi",                  target: "Le Wi-Fi" },
      { id: "fr-v-b1-4-c04", english: "To send a message",      target: "Envoyer un message" },
      { id: "fr-v-b1-4-c05", english: "Social media",           target: "Les réseaux sociaux" },
      { id: "fr-v-b1-4-c06", english: "To download",            target: "Télécharger" },
      { id: "fr-v-b1-4-c07", english: "An app",                 target: "Une appli", alternatives: ["Une application"] },
      { id: "fr-v-b1-4-c08", english: "A computer",             target: "Un ordinateur" },
      { id: "fr-v-b1-4-c09", english: "A screen",               target: "Un écran" },
      { id: "fr-v-b1-4-c10", english: "A password",             target: "Un mot de passe" },
      { id: "fr-v-b1-4-c11", english: "To charge the phone",    target: "Charger le téléphone" },
      { id: "fr-v-b1-4-c12", english: "It doesn't work",        target: "Ça ne marche pas" },
      { id: "fr-v-b1-4-c13", english: "To book online",         target: "Réserver en ligne" },
      { id: "fr-v-b1-4-c14", english: "A video call",           target: "Un appel vidéo" },
      { id: "fr-v-b1-4-c15", english: "A notification",         target: "Une notification" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FRENCH — PHRASE LEVELS
// ─────────────────────────────────────────────────────────────────────────────

export const phraseLevels: Level[] = [

  // ── A1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-a1-1",
    title: "A1 · Introducing yourself",
    cefr: "A1",
    cards: [
      { id: "fr-p-a1-1-c01", english: "My name is Dave",        target: "Je m'appelle Dave" },
      { id: "fr-p-a1-1-c02", english: "I am from Uganda",       target: "Je suis ougandais", alternatives: ["Je viens d'Ouganda"] },
      { id: "fr-p-a1-1-c03", english: "I live in Cairo",        target: "J'habite au Caire" },
      { id: "fr-p-a1-1-c04", english: "I am 30 years old",      target: "J'ai trente ans" },
      { id: "fr-p-a1-1-c05", english: "Nice to meet you",       target: "Enchanté" },
      { id: "fr-p-a1-1-c06", english: "How are you? (formal)",  target: "Comment allez-vous" },
      { id: "fr-p-a1-1-c07", english: "How are you? (casual)",  target: "Ça va" },
      { id: "fr-p-a1-1-c08", english: "I'm fine, thanks",       target: "Ça va bien merci" },
      { id: "fr-p-a1-1-c09", english: "And you?",               target: "Et vous", alternatives: ["Et toi"] },
      { id: "fr-p-a1-1-c10", english: "I am a designer",        target: "Je suis designer" },
      { id: "fr-p-a1-1-c11", english: "I am learning French",   target: "J'apprends le français" },
      { id: "fr-p-a1-1-c12", english: "I am married",           target: "Je suis marié", alternatives: ["Je suis célibataire"] },
    ],
  },

  {
    id: "fr-p-a1-2",
    title: "A1 · Survival phrases",
    cefr: "A1",
    cards: [
      { id: "fr-p-a1-2-c01", english: "I don't understand",     target: "Je ne comprends pas" },
      { id: "fr-p-a1-2-c02", english: "Can you repeat?",        target: "Vous pouvez répéter" },
      { id: "fr-p-a1-2-c03", english: "Speak more slowly",      target: "Parlez plus lentement s'il vous plaît" },
      { id: "fr-p-a1-2-c04", english: "Do you speak English?",  target: "Vous parlez anglais" },
      { id: "fr-p-a1-2-c05", english: "I speak a little French",target: "Je parle un peu français" },
      { id: "fr-p-a1-2-c06", english: "Where is the bathroom?", target: "Où sont les toilettes" },
      { id: "fr-p-a1-2-c07", english: "How much does it cost?", target: "C'est combien" },
      { id: "fr-p-a1-2-c08", english: "I would like...",        target: "Je voudrais" },
      { id: "fr-p-a1-2-c09", english: "Do you have...?",        target: "Vous avez" },
      { id: "fr-p-a1-2-c10", english: "Help!",                  target: "Au secours" },
      { id: "fr-p-a1-2-c11", english: "I am lost",              target: "Je suis perdu" },
      { id: "fr-p-a1-2-c12", english: "Call the police!",       target: "Appelez la police" },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-a2-1",
    title: "A2 · Making plans",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-1-c01", english: "Are you free tonight?",  target: "Tu es libre ce soir" },
      { id: "fr-p-a2-1-c02", english: "Do you want to come?",   target: "Tu veux venir" },
      { id: "fr-p-a2-1-c03", english: "I'd love to",            target: "Avec plaisir", alternatives: ["J'adorerais"] },
      { id: "fr-p-a2-1-c04", english: "Sorry, I can't",         target: "Désolé je ne peux pas" },
      { id: "fr-p-a2-1-c05", english: "Maybe another time",     target: "Peut-être une autre fois" },
      { id: "fr-p-a2-1-c06", english: "Let's meet at...",       target: "On se retrouve à" },
      { id: "fr-p-a2-1-c07", english: "I'll be there at 8",     target: "Je serai là à huit heures" },
      { id: "fr-p-a2-1-c08", english: "I'm running late",       target: "Je suis en retard" },
      { id: "fr-p-a2-1-c09", english: "I had a great time",     target: "Je me suis bien amusé" },
      { id: "fr-p-a2-1-c10", english: "It was really good",     target: "C'était vraiment bien" },
      { id: "fr-p-a2-1-c11", english: "What do you want to do?",target: "Qu'est-ce que tu veux faire" },
      { id: "fr-p-a2-1-c12", english: "I prefer...",            target: "Je préfère" },
    ],
  },

  {
    id: "fr-p-a2-2",
    title: "A2 · Talking about the past",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-2-c01", english: "I went to...",           target: "Je suis allé à" },
      { id: "fr-p-a2-2-c02", english: "I ate",                  target: "J'ai mangé" },
      { id: "fr-p-a2-2-c03", english: "I saw",                  target: "J'ai vu" },
      { id: "fr-p-a2-2-c04", english: "I did / I made",         target: "J'ai fait" },
      { id: "fr-p-a2-2-c05", english: "I bought",               target: "J'ai acheté" },
      { id: "fr-p-a2-2-c06", english: "I came back",            target: "Je suis rentré" },
      { id: "fr-p-a2-2-c07", english: "Yesterday I...",         target: "Hier j'ai" },
      { id: "fr-p-a2-2-c08", english: "Last weekend",           target: "Le week-end dernier" },
      { id: "fr-p-a2-2-c09", english: "It was (description)",   target: "C'était" },
      { id: "fr-p-a2-2-c10", english: "There was",              target: "Il y avait" },
      { id: "fr-p-a2-2-c11", english: "I didn't...",            target: "Je n'ai pas" },
      { id: "fr-p-a2-2-c12", english: "Did you...?",            target: "Tu as", alternatives: ["Vous avez"] },
    ],
  },

  {
    id: "fr-p-a2-3",
    title: "A2 · At the café",
    cefr: "A2",
    cards: [
      { id: "fr-p-a2-3-c01", english: "A coffee please",        target: "Un café s'il vous plaît" },
      { id: "fr-p-a2-3-c02", english: "What would you like?",   target: "Vous désirez" },
      { id: "fr-p-a2-3-c03", english: "The bill please",        target: "L'addition s'il vous plaît" },
      { id: "fr-p-a2-3-c04", english: "A table for two",        target: "Une table pour deux" },
      { id: "fr-p-a2-3-c05", english: "Is service included?",   target: "Le service est compris" },
      { id: "fr-p-a2-3-c06", english: "Do you have a menu?",    target: "Vous avez la carte" },
      { id: "fr-p-a2-3-c07", english: "I'll have the same",     target: "La même chose pour moi" },
      { id: "fr-p-a2-3-c08", english: "Enjoy your meal!",       target: "Bon appétit" },
      { id: "fr-p-a2-3-c09", english: "I'm vegetarian",         target: "Je suis végétarien" },
      { id: "fr-p-a2-3-c10", english: "Without meat please",    target: "Sans viande s'il vous plaît" },
      { id: "fr-p-a2-3-c11", english: "It was delicious",       target: "C'était délicieux" },
      { id: "fr-p-a2-3-c12", english: "Do you take card?",      target: "Vous prenez la carte" },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────
  {
    id: "fr-p-b1-1",
    title: "B1 · Opinions & debate",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-1-c01", english: "I agree",                target: "Je suis d'accord" },
      { id: "fr-p-b1-1-c02", english: "I don't agree",          target: "Je ne suis pas d'accord" },
      { id: "fr-p-b1-1-c03", english: "You're right",           target: "Tu as raison", alternatives: ["Vous avez raison"] },
      { id: "fr-p-b1-1-c04", english: "You're wrong",           target: "Tu as tort" },
      { id: "fr-p-b1-1-c05", english: "I find that...",         target: "Je trouve que" },
      { id: "fr-p-b1-1-c06", english: "It seems to me that...", target: "Il me semble que" },
      { id: "fr-p-b1-1-c07", english: "I'm not sure",           target: "Je ne suis pas sûr" },
      { id: "fr-p-b1-1-c08", english: "That depends on...",     target: "Ça dépend de" },
      { id: "fr-p-b1-1-c09", english: "That's a good point",    target: "C'est un bon point" },
      { id: "fr-p-b1-1-c10", english: "I hadn't thought of that",target: "Je n'y avais pas pensé" },
      { id: "fr-p-b1-1-c11", english: "Let me explain",         target: "Laisse-moi expliquer" },
      { id: "fr-p-b1-1-c12", english: "What do you think?",     target: "Qu'est-ce que tu en penses" },
      { id: "fr-p-b1-1-c13", english: "Personally I think...",  target: "Personnellement je pense que" },
      { id: "fr-p-b1-1-c14", english: "On one hand...",         target: "D'un côté", alternatives: ["De l'autre"] },
    ],
  },

  {
    id: "fr-p-b1-2",
    title: "B1 · Talking about the future",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-2-c01", english: "I'm going to...",        target: "Je vais" },
      { id: "fr-p-b1-2-c02", english: "I plan to...",           target: "Je compte", alternatives: ["J'ai l'intention de"] },
      { id: "fr-p-b1-2-c03", english: "I hope to...",           target: "J'espère" },
      { id: "fr-p-b1-2-c04", english: "I would like to...",     target: "J'aimerais" },
      { id: "fr-p-b1-2-c05", english: "If I have time, I will", target: "Si j'ai le temps je vais" },
      { id: "fr-p-b1-2-c06", english: "One day I want to...",   target: "Un jour je veux" },
      { id: "fr-p-b1-2-c07", english: "Next year",              target: "L'année prochaine" },
      { id: "fr-p-b1-2-c08", english: "In the future",          target: "À l'avenir", alternatives: ["Dans le futur"] },
      { id: "fr-p-b1-2-c09", english: "My dream is to...",      target: "Mon rêve c'est de" },
      { id: "fr-p-b1-2-c10", english: "It's not decided yet",   target: "Ce n'est pas encore décidé" },
      { id: "fr-p-b1-2-c11", english: "We'll see",              target: "On verra" },
      { id: "fr-p-b1-2-c12", english: "It's possible that...",  target: "Il est possible que" },
    ],
  },

  {
    id: "fr-p-b1-3",
    title: "B1 · Complaints & requests",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-3-c01", english: "There's a problem with", target: "Il y a un problème avec" },
      { id: "fr-p-b1-3-c02", english: "This doesn't work",      target: "Ça ne fonctionne pas" },
      { id: "fr-p-b1-3-c03", english: "I ordered...",           target: "J'ai commandé" },
      { id: "fr-p-b1-3-c04", english: "Could you...?",          target: "Pourriez-vous", alternatives: ["Tu pourrais"] },
      { id: "fr-p-b1-3-c05", english: "Would it be possible?",  target: "Ce serait possible de" },
      { id: "fr-p-b1-3-c06", english: "I'm not satisfied",      target: "Je ne suis pas satisfait" },
      { id: "fr-p-b1-3-c07", english: "I'd like a refund",      target: "Je voudrais être remboursé" },
      { id: "fr-p-b1-3-c08", english: "It's not what I expected",target: "Ce n'est pas ce que j'attendais" },
      { id: "fr-p-b1-3-c09", english: "I've been waiting for",  target: "J'attends depuis" },
      { id: "fr-p-b1-3-c10", english: "Could you fix this?",    target: "Vous pouvez régler ça" },
      { id: "fr-p-b1-3-c11", english: "Thank you for your help",target: "Merci pour votre aide" },
      { id: "fr-p-b1-3-c12", english: "Can I speak to a manager?",target: "Je peux parler au responsable" },
    ],
  },

  {
    id: "fr-p-b1-4",
    title: "B1 · Storytelling",
    cefr: "B1",
    cards: [
      { id: "fr-p-b1-4-c01", english: "So, basically...",       target: "Alors voilà" },
      { id: "fr-p-b1-4-c02", english: "At first",               target: "D'abord", alternatives: ["Au début"] },
      { id: "fr-p-b1-4-c03", english: "Then / after that",      target: "Ensuite", alternatives: ["Après"] },
      { id: "fr-p-b1-4-c04", english: "Finally / in the end",   target: "Finalement", alternatives: ["À la fin"] },
      { id: "fr-p-b1-4-c05", english: "Suddenly",               target: "Tout à coup", alternatives: ["Soudain"] },
      { id: "fr-p-b1-4-c06", english: "At the same time",       target: "En même temps" },
      { id: "fr-p-b1-4-c07", english: "I was telling myself...",target: "Je me disais que" },
      { id: "fr-p-b1-4-c08", english: "Can you believe it?",    target: "Tu y crois toi" },
      { id: "fr-p-b1-4-c09", english: "Turns out...",           target: "Il s'avère que", alternatives: ["Du coup"] },
      { id: "fr-p-b1-4-c10", english: "Long story short",       target: "Bref" },
      { id: "fr-p-b1-4-c11", english: "The best part is...",    target: "Le mieux c'est que" },
      { id: "fr-p-b1-4-c12", english: "I couldn't believe it",  target: "Je n'en revenais pas" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// ARABIC
// ─────────────────────────────────────────────────────────────────────────────

export const arabicVocabularyLevels: Level[] = [
  {
    id: "ar-v-a1-1",
    title: "A1 · Greetings",
    cefr: "A1",
    cards: [
      { id: "ar-v1",  english: "Hello",          arabic: "مرحبا",           target: "مرحبا" },
      { id: "ar-v2",  english: "Goodbye",         arabic: "مع السلامة",      target: "مع السلامة" },
      { id: "ar-v3",  english: "Yes",             arabic: "نعم",             target: "نعم" },
      { id: "ar-v4",  english: "No",              arabic: "لا",              target: "لا" },
      { id: "ar-v5",  english: "Thank you",       arabic: "شكرا",            target: "شكرا" },
      { id: "ar-v6",  english: "Welcome",         arabic: "أهلا وسهلا",      target: "أهلا وسهلا" },
      { id: "ar-v7",  english: "Good morning",    arabic: "صباح الخير",      target: "صباح الخير" },
      { id: "ar-v8",  english: "Good evening",    arabic: "مساء الخير",      target: "مساء الخير" },
      { id: "ar-v9",  english: "Good night",      arabic: "تصبح على خير",    target: "تصبح على خير" },
      { id: "ar-v10", english: "Please",          arabic: "من فضلك",         target: "من فضلك" },
      { id: "ar-v11", english: "Sorry",           arabic: "آسف",             target: "آسف" },
      { id: "ar-v12", english: "Excuse me",       arabic: "عفوا",            target: "عفوا" },
      { id: "ar-v13", english: "How are you?",    arabic: "كيف حالك",        target: "كيف حالك" },
      { id: "ar-v14", english: "Fine",            arabic: "بخير",            target: "بخير" },
      { id: "ar-v15", english: "My name is",      arabic: "اسمي",            target: "اسمي" },
    ],
  },
  {
    id: "ar-v-a1-2",
    title: "A1 · Essentials",
    cefr: "A1",
    cards: [
      { id: "ar-v16", english: "Water",   arabic: "ماء",      target: "ماء" },
      { id: "ar-v17", english: "Food",    arabic: "طعام",     target: "طعام" },
      { id: "ar-v18", english: "House",   arabic: "بيت",      target: "بيت" },
      { id: "ar-v19", english: "Work",    arabic: "عمل",      target: "عمل" },
      { id: "ar-v20", english: "Friend",  arabic: "صديق",     target: "صديق" },
      { id: "ar-v21", english: "Family",  arabic: "عائلة",    target: "عائلة" },
      { id: "ar-v22", english: "Money",   arabic: "مال",      target: "مال" },
      { id: "ar-v23", english: "Time",    arabic: "وقت",      target: "وقت" },
      { id: "ar-v24", english: "Day",     arabic: "يوم",      target: "يوم" },
      { id: "ar-v25", english: "Night",   arabic: "ليل",      target: "ليل" },
      { id: "ar-v26", english: "Today",   arabic: "اليوم",    target: "اليوم" },
      { id: "ar-v27", english: "Tomorrow",arabic: "غدا",      target: "غدا" },
      { id: "ar-v28", english: "Help",    arabic: "مساعدة",   target: "مساعدة" },
      { id: "ar-v29", english: "School",  arabic: "مدرسة",    target: "مدرسة" },
      { id: "ar-v30", english: "City",    arabic: "مدينة",    target: "مدينة" },
    ],
  },
  {
    id: "ar-v-a1-3",
    title: "A1 · Numbers",
    cefr: "A1",
    cards: [
      { id: "ar-v31", english: "One",   arabic: "واحد",   target: "واحد" },
      { id: "ar-v32", english: "Two",   arabic: "اثنان",  target: "اثنان" },
      { id: "ar-v33", english: "Three", arabic: "ثلاثة",  target: "ثلاثة" },
      { id: "ar-v34", english: "Four",  arabic: "أربعة",  target: "أربعة" },
      { id: "ar-v35", english: "Five",  arabic: "خمسة",   target: "خمسة" },
      { id: "ar-v36", english: "Six",   arabic: "ستة",    target: "ستة" },
      { id: "ar-v37", english: "Seven", arabic: "سبعة",   target: "سبعة" },
      { id: "ar-v38", english: "Eight", arabic: "ثمانية", target: "ثمانية" },
      { id: "ar-v39", english: "Nine",  arabic: "تسعة",   target: "تسعة" },
      { id: "ar-v40", english: "Ten",   arabic: "عشرة",   target: "عشرة" },
    ],
  },
];

export const arabicPhraseLevels: Level[] = [
  {
    id: "ar-p-a1-1",
    title: "A1 · Introductions",
    cefr: "A1",
    cards: [
      { id: "ar-p1", english: "What is your name?",       arabic: "ما اسمك؟",                target: "ما اسمك؟" },
      { id: "ar-p2", english: "Where are you from?",      arabic: "من أين أنت؟",             target: "من أين أنت؟" },
      { id: "ar-p3", english: "I am from...",             arabic: "أنا من",                  target: "أنا من" },
      { id: "ar-p4", english: "Nice to meet you",         arabic: "تشرفت بمعرفتك",           target: "تشرفت بمعرفتك" },
      { id: "ar-p5", english: "I speak a little Arabic",  arabic: "أتكلم قليلا من العربية", target: "أتكلم قليلا من العربية" },
      { id: "ar-p6", english: "I am learning Arabic",     arabic: "أتعلم العربية",           target: "أتعلم العربية" },
    ],
  },
  {
    id: "ar-p-a1-2",
    title: "A1 · Getting around",
    cefr: "A1",
    cards: [
      { id: "ar-p7",  english: "Where is the bathroom?",  arabic: "أين الحمام؟",            target: "أين الحمام؟" },
      { id: "ar-p8",  english: "How much does this cost?",arabic: "كم يكلف هذا؟",            target: "كم يكلف هذا؟" },
      { id: "ar-p9",  english: "I don't understand",      arabic: "لا أفهم",                 target: "لا أفهم" },
      { id: "ar-p10", english: "Can you help me?",        arabic: "هل يمكنك مساعدتي؟",       target: "هل يمكنك مساعدتي؟" },
      { id: "ar-p11", english: "Speak slowly please",     arabic: "تكلم ببطء من فضلك",       target: "تكلم ببطء من فضلك" },
      { id: "ar-p12", english: "I would like...",         arabic: "أريد",                    target: "أريد" },
      { id: "ar-p13", english: "Where is the hotel?",     arabic: "أين الفندق؟",             target: "أين الفندق؟" },
    ],
  },
];
